---
- name: Install nfs-kernel-server
  tags: nfs
  apt:
    name: nfs-kernel-server

- name: Create NFS exports
  tags: config, nfs
  copy:
    src: ansible.exports
    dest: /etc/exports.d/ansible.exports
    mode: 0600
  notify: Restart nfs-server
