version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: "mongo:latest"
    restart: unless-stopped
    volumes:
      - "mongodb_data:/data/db"

  elasticsearch:
    container_name: elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
    restart: unless-stopped
    environment:
      ES_JAVA_OPTS: "-Xms8g -Xmx8g -Dlog4j2.formatMsgNoLookups=true"
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      http.host: "0.0.0.0"
      action.auto_create_index: "false"
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - "es_data:/usr/share/elasticsearch/data"


  graylog:
    container_name: graylog
    image: "graylog/graylog:4.3"
    restart: unless-stopped
    depends_on:
      elasticsearch:
        condition: "service_started"
      mongodb:
        condition: "service_started"
    entrypoint: "/usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      GRAYLOG_PASSWORD_SECRET: ${GRAYLOG_PASSWORD_SECRET}
      GRAYLOG_ROOT_PASSWORD_SHA2: ${GRAYLOG_ROOT_PASSWORD_SHA2}
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://lyra:9000/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
      GRAYLOG_TIMEZONE: {{ timezone }}
      GRAYLOG_ROOT_TIMEZONE: {{ timezone }}
    ports:
    - "514:5140/udp"   # Syslog
    - "514:5140/tcp"   # Syslog
    - "12201:12201/udp"   # GELF
    - "80:9000/tcp"   # Server API

    volumes:
      - "graylog_data:/usr/share/graylog/data/data"
      - "graylog_journal:/usr/share/graylog/data/journal"
      - /etc/localtime:/etc/localtime:ro

volumes:
  mongodb_data:
  es_data:
  graylog_data:
  graylog_journal: