---
- name: Create zfs-load-key service
  tags: config, zfs
  copy:
    src: zfs-load-key.service
    dest: /etc/systemd/system/zfs-load-key.service
    mode: "0755"

- name: Enable zfs-load-key service
  tags: config, zfs
  service:
    name: zfs-load-key
    enabled: true
    state: started
