---
- name: Create zfs-load-key service
  tags: config, zfs
  copy:
    src: zfs-load-key.service
    dest: /etc/systemd/system/zfs-load-key.service
    mode: "0755"

- name: Enable zfs-load-key service
  tags: config, zfs
  service:
    name: zfs-load-key
    enabled: true
    state: started

- name: Set ARC size to 2-8 GB
  tags: config, zfs
  blockinfile:
    path: /etc/modprobe.d/zfs.conf
    create: true
    mode: "0644"
    block: |-
      options zfs zfs_arc_max=8589934592
      options zfs zfs_arc_min=2147483648
