---
- name: Install sanoid and syncoid
  tags: pkg, syncoid, sanoid
  package:
    name:
      - sanoid

- name: Create sanoid config dir
  tags: config, sanoid
  file:
    path: /etc/sanoid
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Configure sanoid
  tags: config, sanoid
  copy:
    src: "{{ inventory_hostname }}/sanoid.conf"
    dest: /etc/sanoid/sanoid.conf
    mode: "0644"
  notify: Restart sanoid

- name: Add nvme replication cron job
  tags: config, syncoid
  ansible.builtin.cron:
    name: Sync nvme/enc to hdd/enc
    minute: "2"
    hour: "2"
    # No -f - obsolete datasets will need to be deleted on hdd manually,
    # but I can't accidentally delete a dataset and lose it in both places.
    job: /usr/sbin/syncoid -r --skip-parent --no-sync-snap nvme/enc hdd/enc

# Disabled while I'm living that metered connections lyfe :(
#
# - name: Add remote backup cron job
#   tags: config, syncoid
#   ansible.builtin.cron:
#     name: Sync hdd to remote server
#     minute: "0"
#     hour: "4"
#     job: >
#       /usr/sbin/syncoid -r --no-sync-snap --skip-parent  --exclude {{ remote_exclude_dir }} --sendoptions=w --sshport 1984 --sshkey /root/.ssh/id_rsa  hdd/enc
#       aven@{{ backup_host }}:hdd/enc
