networks:
  web:

services:
  beaverhabits:
    container_name: beaverhabits
    image: daya0576/beaverhabits:latest
    restart: unless-stopped
    user: 4013:4013

    networks:
      web:

    environment:
      MAX_USER_COUNT: 1
      ENABLE_IOS_STANDALONE: true
      HABITS_STORAGE: DATABASE
      INDEX_SHOW_HABIT_COUNT: true

    volumes:
      - "{{ app_root }}/beaverhabits:/app/.user/"

    labels:
      traefik.enable: true
      traefik.http.routers.habits.rule: Host(`habits.{{ tertiary_domain }}`)
      traefik.http.routers.habits.entrypoints: https
      traefik.http.routers.habits.tls.certresolver: default
      traefik.http.services.habits.loadbalancer.server.port: 8080
      homepage.group: Apps
      homepage.name: Habit tracking
      homepage.icon: beaverhabits.png
      homepage.href: https://habits.{{ tertiary_domain }}/
      homepage.weight: 17
      homepage.description: Beaver Habits
      homepage.siteMonitor: http://beaverhabits:8945