networks:
  web:
  drone:

services:
  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    restart: unless-stopped

    networks:
      - web

    environment:
      USER_UID: 4002
      USER_GID: 4002
      GITEA__SERVER__ROOT_URL: https://git.{{ tertiary_domain }}
      GITEA__SERVICE__DISABLE_REGISTRATION: true
      GITEA__MIGRATIONS__ALLOW_LOCALNETWORKS: true
      GITEA__INDEXER__REPO_INDEXER_ENABLED: true
      GITEA__WEBHOOK__ALLOWED_HOST_LIST: "*.{{ tertiary_domain }}"

    volumes:
      - "{{ app_root }}/gitea:/data"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    ports:
      - "1108:22"

    labels:
      traefik.enable: true
      traefik.http.routers.git.rule: Host(`git.{{ tertiary_domain }}`)
      traefik.http.routers.git.entrypoints: https
      traefik.http.routers.git.tls.certresolver: default
      traefik.http.services.git.loadbalancer.server.port: 80
      traefik.http.routers.git.middlewares: authelia
      homepage.group: Apps
      homepage.name: Git hosting
      homepage.icon: gitea.png
      homepage.href: https://git.{{ tertiary_domain }}/
      homepage.description: Gitea
      homepage.siteMonitor: http://gitea
      homepage.weight: 50


  drone:
    container_name: drone
    image: drone/drone:2
    restart: unless-stopped
    user: 4002:4002

    networks:
      - web
      - drone

    env_file: drone.env
    environment:
      DRONE_GITEA_SERVER: https://git.{{ tertiary_domain }}
      DRONE_SERVER_HOST: drone.{{ tertiary_domain }}
      DRONE_SERVER_PROTO: https
      DRONE_DATADOG_ENABLED: false

    volumes:
      - "{{ app_root }}/drone:/data"

    labels:
      traefik.enable: true
      traefik.http.routers.drone.rule: Host(`drone.{{ tertiary_domain }}`)
      traefik.http.routers.drone.entrypoints: https
      traefik.http.routers.drone.tls.certresolver: default
      traefik.http.services.drone.loadbalancer.server.port: 80
      traefik.http.routers.drone.middlewares: authelia
      homepage.group: Apps
      homepage.name: CI/CD
      homepage.icon: drone.png
      homepage.href: https://drone.{{ tertiary_domain }}/
      homepage.description: Drone
      homepage.siteMonitor: http://drone
      homepage.weight: 55


  runner:
    container_name: runner
    restart: unless-stopped
    image: drone/drone-runner-docker:1

    networks: 
      - drone

    env_file: drone.env
    environment:
      DRONE_RPC_PROTO: http
      DRONE_RPC_HOST: drone
      DRONE_RUNNER_CAPACITY: 2
      DRONE_RUNNER_NAME: roger-bannister

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
