networks:
  web:
  docker-socket:

services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest

    restart: unless-stopped

    networks:
      - web
      - docker-socket

    environment:
      PUID: 4005
      PGID: 4005
      LOG_LEVEL: warning
      HOMEPAGE_ALLOWED_HOSTS: dash.{{ tertiary_domain }}

    volumes:
      - "{{ app_root }}/homepage/config:/app/config"
      - "{{ app_root }}/homepage/icons:/app/public/icons"

    healthcheck:
      start_interval: 5s

    labels:
      traefik.enable: true
      traefik.http.routers.dash.rule: Host(`dash.{{ tertiary_domain }}`)
      traefik.http.routers.dash.entrypoints: https
      traefik.http.routers.dash.tls.certresolver: default
      traefik.http.services.dash.loadbalancer.server.port: 3000
      traefik.http.routers.dash.middlewares: authelia