networks:
  immich:
  web:

services:
  immich_server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    user: 4009:4009

    # Quicksync
    devices:
          - /dev/dri:/dev/dri
      
    volumes:
      - ${IMMICH_DATA_LOCATION}:/usr/src/app/upload
      - ${IMMICH_UPLOAD_LOCATION}:/usr/src/app/upload/library
      - ${IMMICH_IMPORT_LOCATION}:/mnt/aven:ro
    env_file:
      - immich.env
    depends_on:
      - immich_redis
      - immich_postgres
    networks:
      immich:
      web:
    restart: unless-stopped

    labels:
      traefik.enable: true
      traefik.http.routers.pic.rule: Host(`pic.{{ tertiary_domain }}`)
      traefik.http.routers.pic.entrypoints: https
      traefik.http.routers.pic.tls.certresolver: default
      traefik.http.services.pic.loadbalancer.server.port: 3001
      homepage.group: Apps
      homepage.name: Photo management
      homepage.icon: immich.png
      homepage.href: https://pic.{{ tertiary_domain }}/
      homepage.weight: 10
      homepage.description: Immich
      homepage.siteMonitor: http://immich_server:3001
      homepage.widget.type: immich
      homepage.widget.url: http://immich_server:3001
      homepage.widget.key: ${IMMICH_API_KEY}
      homepage.widget.fields: '["photos", "videos"]'

  immich_machine_learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    user: 4009:4009
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

    volumes:
      - ${IMMICH_DATA_LOCATION}:/usr/src/app/upload
      - ${IMMICH_UPLOAD_LOCATION}:/usr/src/app/upload/library
      - ${IMMICH_IMPORT_LOCATION}:/mnt/aven:ro
      - "{{ app_root }}/immich/ml_cache:/cache"
    env_file:
      - immich.env
    networks:
      immich:
    restart: unless-stopped

  immich_redis:
    container_name: immich_redis
    image: redis:6.2
    user: 4009:4009
    restart: unless-stopped
    networks:
      immich:


  immich_postgres:
    container_name: immich_postgres
    user: 4009:4009
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0

    env_file:
      - immich.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    networks:
      immich:
    volumes:
      - "{{ app_root }}/immich/postgres:/var/lib/postgresql/data"
    restart: unless-stopped
