networks: 
  web:

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    # network_mode: 'host'
    restart: 'unless-stopped'

    networks:
      web:

    # Quicksync
    devices:
      - /dev/dri:/dev/dri

    ports:
      # Service discovery/DLNA
      - 1900:1900/udp
      # Client discovery
      - 7359:7359/udp

    volumes:
      - "{{ app_root }}/jellyfin/config:/config"
      - "{{ app_root }}/jellyfin/cache:/cache"
      # Read-only breaks trickplay
      - type: bind
        source: "{{ app_root }}/pinchflat/downloads"
        target: /media/pinchflat
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    environment:
      JELLYFIN_PublishedServerUrl: media.{{ tertiary_domain }}
      
    labels:
      traefik.enable: true
      traefik.http.routers.media.rule: Host(`media.{{ tertiary_domain }}`)
      traefik.http.routers.media.tls.certresolver: default
      traefik.http.services.media.loadbalancer.server.port: 8096
      homepage.group: Apps
      homepage.name: Media
      homepage.icon: jellyfin.png
      homepage.href: https://media.{{ tertiary_domain }}/
      homepage.weight: 61
      homepage.description: Jellyfin
      homepage.siteMonitor: http://jellyfin:8096