networks:
  web:
  karakeep:
  ai:

services:
  karakeep:
    container_name: karakeep
    image: ghcr.io/karakeep-app/karakeep:release
    restart: unless-stopped
    # TODO Pending https://github.com/karakeep-app/karakeep/issues/606
    # user: 4014:4014

    networks:
      web:
      karakeep:
      ai:

    volumes:
      - "{{app_root}}/karakeep/karakeep:/data"

    env_file:
      - karakeep.env

    environment:
      NEXTAUTH_URL: https://bookmarks.{{ tertiary_domain }}
      MEILI_ADDR: http://karakeep_meilisearch:7700
      BROWSER_WEB_URL: http://karakeep_chrome:9222
      DATA_DIR: /data 
      DISABLE_SIGNUPS: true

      OLLAMA_BASE_URL: http://ollama:11434
      INFERENCE_TEXT_MODEL: llama3.2:latest
      INFERENCE_IMAGE_MODEL: llava:latest
      EMBEDDING_TEXT_MODEL: nomic-embed-text
      INFERENCE_CONTEXT_LENGTH: 131072

      DISABLE_PASSWORD_AUTH: true
      OAUTH_WELLKNOWN_URL: https://auth.{{ tertiary_domain }}
      OAUTH_PROVIDER_NAME: auth.{{ tertiary_domain }}
      # Allowing signin to existing accounts with SSO
      OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: true

    labels:
      traefik.enable: true
      traefik.http.routers.karakeep.rule: Host(`bookmarks.{{ tertiary_domain }}`)
      traefik.http.routers.karakeep.tls.certresolver: default
      traefik.http.services.karakeep.loadbalancer.server.port: 3000
      homepage.group: Apps
      homepage.name: Bookmarks
      homepage.icon: karakeep.png
      homepage.href: https://bookmarks.{{ tertiary_domain }}/
      homepage.weight: 18
      homepage.description: karakeep
      homepage.siteMonitor: http://karakeep:3000

  karakeep_chrome:
    container_name: karakeep_chrome
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    # user: 4014:4014

    networks:
      karakeep:
    
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars

  karakeep_meilisearch:
    container_name: karakeep_meilisearch
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    # user: 4014:4014

    networks:
      karakeep:

    env_file:
      - karakeep.env
    environment:
      MEILI_NO_ANALYTICS: true
    volumes:
      - "{{app_root}}/karakeep/meilisearch:/meili_data"