networks:
  web:

services:
  pinchflat:
    container_name: pinchflat
    image: ghcr.io/kieraneglin/pinchflat:latest
    restart: unless-stopped
    user: 4020:4020

    networks:
      web:

    environment:
      TZ: {{ timezone }}
      LOG_LEVEL: info
      YT_DLP_WORKER_CONCURRENCY: 1

    volumes:
      - "{{ app_root }}/pinchflat/config:/config"
      - "{{ app_root }}/pinchflat/downloads:/downloads"

    labels:
      traefik.enable: true
      traefik.http.routers.yt.rule: Host(`yt.{{ tertiary_domain }}`)
      traefik.http.routers.yt.entrypoints: https
      traefik.http.routers.yt.tls.certresolver: default
      traefik.http.services.yt.loadbalancer.server.port: 8945
      homepage.group: Apps
      homepage.name: YouTube downloads
      homepage.icon: pinchflat.png
      homepage.href: https://yt.{{ tertiary_domain }}/
      homepage.weight: 15
      homepage.description: Pinchflat
      homepage.siteMonitor: http://pinchflat:8945