networks:
  web:
  docker-socket:

services:
  docker-socket-proxy:
    container_name: docker-socket-proxy
    image: ghcr.io/tecnativa/docker-socket-proxy:0.1.1
    restart: unless-stopped

    environment:
      CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      TASKS: 1
      POST: 0 # default, prevents making changes

    networks:
      - docker-socket

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  traefik:
    container_name: traefik
    image: traefik:latest
    user: 4001:4001
    restart: on-failure:3

    depends_on:
      - docker-socket-proxy

    ports:
      - 80:80
      - 443:443

    env_file: 
      - traefik.env

    networks:
      - web
      - docker-socket

    volumes:
      - "{{ app_root }}/traefik/traefik.yml:/traefik.yml"
      - "{{ app_root }}/traefik/dynamic_conf.yml:/dynamic_conf.yml"
      - "{{ app_root }}/traefik/acme.json:/acme.json"
      - /etc/localtime:/etc/localtime:ro

    labels:
      traefik.enable: true
      traefik.http.routers.api.rule: Host(`proxy.{{ tertiary_domain }}`)
      traefik.http.routers.api.tls.certresolver: default
      traefik.http.routers.api.service: api@internal
      traefik.http.routers.api.middlewares: auth
      traefik.http.middlewares.auth.basicauth.users: ${TRAEFIK_USERS}
      # Below will cause Traefik to request a wildcard cert
      traefik.http.routers.api.tls.domains[0].main: "*.{{ tertiary_domain }}"
      homepage.group: Admin
      homepage.name: Reverse proxy
      homepage.icon: traefik.png
      homepage.href: https://proxy.{{ tertiary_domain }}/
      homepage.description: Traefik
      homepage.siteMonitor: https://proxy.{{ tertiary_domain }}
      homepage.widget.type: traefik
      homepage.widget.url: https://proxy.{{ tertiary_domain }}
      homepage.widget.username: aven 
      homepage.widget.password: ${TRAEFIK_PASSWORD}
      homepage.weight: 25