---
- name: Install rclone
  tags: rclone, pkg
  package:
    name:
      - rclone

- name: Create config dirs
  tags: config, rclone
  file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
  loop:
    - /root/.config/backblaze/
    - /root/.config/rclone/

- name: Configure rclone
  tags: config, rclone
  copy:
    src: "{{ inventory_hostname }}/rclone.conf"
    dest: /root/.config/rclone/rclone.conf
    mode: "0600"

- name: Create backup script
  tags: config, rclone
  template:
    src: backblaze-backup
    dest: /usr/local/sbin/
    mode: "0500"

- name: Configure backup script
  tags: config, rclone
  copy:
    src: "{{ inventory_hostname }}/excludes.conf"
    dest: /root/.config/backblaze/
    mode: "0600"

- name: Enable cron task
  tags: config, cron, rclone
  cron:
    name: Back up to Backblaze
    minute: "15"
    hour: "3"
    job: /usr/local/sbin/backblaze-backup
