---

- hosts: all
  become: true
  pre_tasks:
  - name: Update index and dist-upgrade
    tags: update
    apt:
      update_cache: yes
      upgrade: dist
  
  tasks:
  - name: Install packages (all)
    apt:
      name:
        - vim
        - zsh
        - tldr
        - kitty-terminfo
        - tmux
        - curl
        - git
        - ufw
      state: latest
  - name: Install packages (VMs)
    apt:
      name: qemu-guest-agent
      state: latest
  - name: Remove unwanted packages
    apt:
      name:
        - nano
        - magic-wormhole
      state: absent
      autoremove: yes

  - name: Update tldr
    tags: update
    shell: "tldr --update"
  - name: Install zsh-grml-config
    tags: zsh, config
    copy:
      src: zshrc
      dest: /etc/zsh/zshrc
      mode: 0644
      owner: root
      group: root 
  - name: Set user shell to zsh
    tags: zsh, config
    user: 
      name: "{{ ansible_user }}"
      shell: /bin/zsh
  - name: Set root shell to zsh
    tags: zsh, config
    user: 
      name: root
      shell: /bin/zsh

  - name: Set sshd config
    tags: sshd
    copy:
      src: sshd_config
      dest: /etc/ssh/sshd_config
      mode: 0644
      owner: root
      group: root
      validate: sshd -t -f %s
    register: sshd
  - name: Reload sshd config
    tags: sshd
    service:
      name: sshd
      state: restarted
    when: sshd.changed


        #TODO: Namecheap mirrors, grub config, .vimrc,
        #      SSH host keys

- hosts: docker
  tasks:
  - name: Install Docker
    apt:
      name:
        - docker-ce
      state: latest

      #TODO: nfs mounts, immutability on mount points
