---
# Do update pre-tasks before anything else...

- hosts: all
  become: true
  gather_facts: true
  ignore_unreachable: true
  pre_tasks:
  - name: Update apt index
    tags: update, upgrade
    when: ansible_os_family == "Debian"
    changed_when: false
    apt:
      update_cache: yes
  - name: Run apt dist upgrade
    tags: upgrade
    when: ansible_os_family == "Debian"
    apt:
      upgrade: dist
      autoremove: yes
  - name: Update pacman index
    tags: update, upgrade
    changed_when: false
    when: ansible_os_family == "Archlinux"
    community.general.pacman:
      update_cache: yes
  - name: Run pacman upgrade
    tags: upgrade
    when: ansible_os_family == "Archlinux"
    community.general.pacman:
      upgrade: yes
  
# ...then run base config on all machines...

- hosts: all
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - base

# ...and finally, do role-specific tasks

- hosts: vm
  become: true
  ignore_unreachable: true
  roles:
    - xterm-js

- hosts: docker
  become: true
  ignore_unreachable: true
  roles:
    - geerlingguy.docker
    - nfs_client
    - docker
    - dotfiles_copy
    
- hosts: apps
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles: 
    - mariadb_backup

- hosts: jj
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - dotfiles_copy
    - more_users

- hosts: arch-dev
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - arch-workstation
    - dotfiles_clone

- hosts: fornax
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - arch-workstation
    - arch-laptop
    - dotfiles_clone