---

- hosts: all
  become: true
  pre_tasks:
  - name: Update index and dist-upgrade
    apt:
      update_cache: yes
      upgrade: dist
  
  tasks:
  - name: Install packages
    apt:
      name:
        - vim
        - zsh
        - tldr
        - kitty-terminfo
        - tmux
        - qemu-guest-agent
        - curl
        - git
        - ufw
      state: latest
  - name: Update tldr
    shell: "tldr --update"
  - name: Remove unwanted packages
    apt:
      name:
        - nano
        - magic-wormhole
      state: absent
      autoremove: yes
  - name: Install zsh-grml-config
    tags: zsh, config
    get_url:
      url: https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
      dest: /etc/zsh/zshrc
      mode: 0644
      owner: root
      group: root 
  - name: Set user shell to zsh
    tags: zsh, config
    user: 
      name: "{{ ansible_user }}"
      shell: /bin/zsh
    user: 
      name: root
      shell: /bin/zsh

        #TODO: Namecheap mirrors, SSH config, grub config, .vimrc,
        #      SSH host keys

- hosts: docker
  tasks:
  - name: Install Docker
    apt:
      name:
        - docker-ce
      state: latest

