---
# Do OS-specific pre-tasks before anything else...

- hosts: debian
  become: true
  gather_facts: true
  pre_tasks:
  - name: Update package index
    tags: update, upgrade
    changed_when: false
    apt:
      update_cache: yes
  - name: Run dist-upgrade
    tags: upgrade
    apt:
      upgrade: dist
      autoremove: yes

- hosts: arch
  become: true
  gather_facts: false
  pre_tasks:
  - name: Update package index
    tags: update, upgrade
    changed_when: false
    community.general.pacman:
      update_cache: yes
  - name: Run system upgrade
    tags: upgrade
    community.general.pacman:
      upgrade: yes
  
# ...then run base config on all machines...

- hosts: all
  become: true
  gather_facts: false
  roles:
    - base
    - xterm-js

# ...and finally, do role-specific tasks

- hosts: docker_server
  become: true
  roles:
    - geerlingguy.docker
    - nfs_client
    - docker_server
    - dotfiles_copy
    
- hosts: docker
  become: true
  gather_facts: false
  roles: 
    - mariadb

- hosts: work_server
  become: true
  gather_facts: false
  roles:
    - work_server

- hosts: arch-dev
  become: true
  gather_facts: false
  roles:
    - arch-desktop
    - dotfiles_copy

- hosts: jj
  become: true
  gather_facts: false
  roles:
    - dotfiles_copy
    - more_users

- hosts: seedling
  become: true
  gather_facts: false
  roles:
    - nfs_client
    - dotfiles_copy

# - hosts: bastion
#   become: true
#   gather_facts: false
#   roles:
#     - dotfiles_copy
#     - robertdebock.fail2ban
#     - jnv.mosh