---
# Do OS-specific pre-tasks before anything else...

- hosts: debian
  become: true
  gather_facts: true
  pre_tasks:
  - name: Update package index
    tags: update, upgrade
    changed_when: false
    apt:
      update_cache: yes
  - name: Run dist-upgrade
    tags: upgrade
    apt:
      upgrade: dist
      autoremove: yes

- hosts: arch
  become: true
  gather_facts: false
  pre_tasks:
  - name: Update package index
    tags: update, upgrade
    changed_when: false
    community.general.pacman:
      update_cache: yes
  - name: Run system upgrade
    tags: upgrade
    community.general.pacman:
      upgrade: yes
  
# ...then run base config on all machines...

- hosts: all
  become: true
  gather_facts: false
  vars:
    domain: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35386165613136366338633137663034616632653739306164616365373037386432353635613136
          6239383762656462646436623664386636663139343835620a616333616332626461623462393061
          65373838383434303661643861393239626161323632343363653132613337306665393234383935
          6163326336356631320a333265366561306361393236366133653535373438623337346137323362
          3338
  
  roles:
    - base

# ...and finally, do role-specific tasks

- hosts: docker_server
  become: true
  roles:
    - geerlingguy.docker
    - nfs_client
    - docker_server
    - dotfiles_copy
    - xterm-js
    
- hosts: docker
  become: true
  gather_facts: false
  roles: 
    - mariadb
    - xterm-js

- hosts: work_server
  become: true
  gather_facts: false
  roles:
    - work_server
    - xterm-js

- hosts: arch-dev
  become: true
  gather_facts: false
  roles:
    - arch-workstation
    - dotfiles_copy
    - xterm-js

- hosts: jj
  become: true
  gather_facts: false
  roles:
    - dotfiles_copy
    - more_users
    - xterm-js

- hosts: seedling
  become: true
  gather_facts: false
  roles:
    - nfs_client
    - dotfiles_copy
    - xterm-js

- hosts: fornax
  become: true
  gather_facts: false
  roles:
    - arch-workstation
    - arch-laptop
    - dotfiles_clone