---

- hosts: all
  become: true
  pre_tasks:
  - name: Update package index
    tags: update
    changed_when: false
    apt:
      update_cache: yes

  - name: Run dist-upgrade
    tags: update
    apt:
      upgrade: dist
      autoremove: yes

- hosts: all
  become: true
  roles:
    - base
    
- hosts: docker
  become: true
  roles:
    - geerlingguy.docker
    - docker

- hosts: bastion
  become: true
  roles:
    - bastion