---

- hosts: all
  become: true
  pre_tasks:
  - name: Update package index
    tags: update
    changed_when: false
    apt:
      update_cache: yes

  - name: Run dist-upgrade
    tags: update
    apt:
      upgrade: dist
      autoremove: yes
  roles:
    - base
    
- hosts: docker_server
  become: true
  roles:
    - geerlingguy.docker
    - docker_server

# - hosts: app_server
#   become: true
#   roles:
#     - app_server

# - hosts: game_server
#   become: true
#   roles:
#     - game_server

- hosts: bastion
  become: true
  roles:
    - bastion