---
# Do update pre-tasks before anything else...

- name: Run upgrades
  hosts: all
  become: true
  gather_facts: true
  ignore_unreachable: true
  pre_tasks:
    - name: Update apt index
      tags: update, upgrade
      when: ansible_os_family == "Debian"
      changed_when: false
      apt:
        update_cache: true
    - name: Run apt dist upgrade
      tags: upgrade
      when: ansible_os_family == "Debian"
      apt:
        upgrade: dist
        autoremove: true
    - name: Update pacman index
      tags: update, upgrade
      changed_when: false
      when: ansible_os_family == "Archlinux"
      community.general.pacman:
        update_cache: true
    - name: Run pacman upgrade
      tags: upgrade
      when: ansible_os_family == "Archlinux"
      community.general.pacman:
        upgrade: true

# ...then run base config on all machines...

- name: Base config
  hosts: all
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - base

# ...and finally, do role-specific tasks

- name: Docker roles
  hosts: docker
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - role: geerlingguy.docker
      tags: docker
      vars:
        docker_compose_version: v2.36.0
        docker_daemon_options:
          default-address-pools:
            - base: 172.19.0.0/16
              size: 24
          runtimes:
            nvidia:
              args: []
              path: nvidia-container-runtime
    - docker
    - dotfiles_copy

- name: cepheus
  hosts: cepheus
  become: true
  gather_facts: false
  ignore_unreachable: false
  roles:
    - geerlingguy.ntp
    - inhibit_suspend
    - zigbee_udev
    - zfs
    - syncoid_sanoid
    - backblaze
    - apprise
    - external_backup
    - role: artis3n.tailscale
      tags: tailscale
      vars:
        tailscale_args: --advertise-tags=tag:docker --snat-subnet-routes=false --accept-routes

- name: web01
  hosts: web01
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - backblaze

- name: offsite01
  hosts: offsite01
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - more_users
    - role: artis3n.tailscale
      tags: tailscale
      vars:
        tailscale_args: --advertise-tags=tag:offsite
    - dotfiles_copy

- name: offsite02
  hosts: offsite02
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - zigbee_udev
    - wpa_supplicant
    - role: artis3n.tailscale
      tags: tailscale
      vars:
        tailscale_args: --advertise-tags=tag:offsite
    - dotfiles_copy
    - liveness_monitor

# - name: ixion
#   hosts: ixion
#   become: true
#   gather_facts: false
#   ignore_unreachable: true
#   roles:
#     - arch_workstation
#     - arch_laptop
#     - arch_secureboot
#     - dotfiles_clone
#     - role: artis3n.tailscale
#       tags: tailscale

- name: Host-specific tasks
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Run host-specific tasks
      tags: zfs
      include_tasks:
        file: "{{ item }}"
      with_first_found:
        - files: host_tasks/{{ ansible_hostname }}.yml
          skip: true
