---
# Do update pre-tasks before anything else...

- hosts: all
  become: true
  gather_facts: true
  ignore_unreachable: true
  pre_tasks:
    - name: Update apt index
      tags: update, upgrade
      when: ansible_os_family == "Debian"
      changed_when: false
      apt:
        update_cache: true
    - name: Run apt dist upgrade
      tags: upgrade
      when: ansible_os_family == "Debian"
      apt:
        upgrade: dist
        autoremove: true
    - name: Update pacman index
      tags: update, upgrade
      changed_when: false
      when: ansible_os_family == "Archlinux"
      community.general.pacman:
        update_cache: true
    - name: Run pacman upgrade
      tags: upgrade
      when: ansible_os_family == "Archlinux"
      community.general.pacman:
        upgrade: true

# ...then run base config on all machines...

- hosts: all
  become: true
  ignore_unreachable: true
  roles:
    - base

# ...and finally, do role-specific tasks

- hosts: draco
  become: true
  gather_facts: false
  ignore_unreachable: false
  roles:
    - zfs
    - role: lae.proxmox
      vars:
        pve_reboot_on_kernel_update: false
    - pve_networking
    - nfs_server
    - syncoid_sanoid
    - backblaze
    - more_users
    - remote_decrypt

- hosts: vm
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - xterm_js

- hosts: nfs_clients
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - more_users
    - nfs_client

- hosts: docker
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - geerlingguy.docker
    - docker
    - dotfiles_copy

- hosts: workstations
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - arch_workstation
    - ssh_agent
    - dotfiles_clone
    - artis3n.tailscale

- hosts: apps
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - mariadb_backup

- hosts: dmz-apps
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - role: remote_logs
      vars:
        gelf_docker: true

- hosts: jj
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - dotfiles_copy
    - more_users
    - role: remote_logs
      vars:
        rsyslog_auth: true

- hosts: titania
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - arch_desktop
    - arch_secureboot

- hosts: fornax
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - arch_laptop

- hosts: web1
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - backblaze
    - role: artis3n.tailscale
      tags: tailscale
      vars:
        tailscale_args: --advertise-exit-node --advertise-tags=tag:vps
