---
# Do update pre-tasks before anything else...

- hosts: all
  become: true
  gather_facts: true
  ignore_unreachable: true
  pre_tasks:
    - name: Update apt index
      tags: update, upgrade
      when: ansible_os_family == "Debian"
      changed_when: false
      apt:
        update_cache: true
    - name: Run apt dist upgrade
      tags: upgrade
      when: ansible_os_family == "Debian"
      apt:
        upgrade: dist
        autoremove: true
    - name: Update pacman index
      tags: update, upgrade
      changed_when: false
      when: ansible_os_family == "Archlinux"
      community.general.pacman:
        update_cache: true
    - name: Run pacman upgrade
      tags: upgrade
      when: ansible_os_family == "Archlinux"
      community.general.pacman:
        upgrade: true

# ...then run base config on all machines...

- hosts: all
  become: true
  ignore_unreachable: true
  roles:
    - base

# ...and finally, do role-specific tasks

- hosts: draco
  become: true
  gather_facts: false
  ignore_unreachable: false
  roles:
    - zfs
    - nfs_server
    - syncoid_sanoid
    - backblaze
    - more_users
    - remote_decrypt

- hosts: lyra
  become: True
  serial: 1
  tasks:
    - name: Install bridge-utils
      apt:
        name: bridge-utils

    - name: Configure /etc/network/interfaces
      template:
        src: "{{ interfaces_template }}"
        dest: /etc/network/interfaces
      register: _configure_interfaces

    - name: Configure /etc/resolv.conf
      template:
        src: "{{ resolv_template }}"
        dest: /etc/resolv.conf
      register: _configure_interfaces

    # - block:
    #   - name: Reboot for networking changes
    #     shell: "sleep 5 && shutdown -r now 'Networking changes found, rebooting'"
    #     async: 1
    #     poll: 0

    #   - name: Wait for server to come back online
    #     wait_for_connection:
    #       delay: 15
    #   when: _configure_interfaces is changed

- hosts: lyra
  become: true
  gather_facts: false
  ignore_unreachable: false
  roles:
    - role: geerlingguy.ntp
      vars:
        ntp_manage_config: true
        ntp_timezone: America/Chicago
    - role: lae.proxmox
      vars:
        - pve_group: all
        - pve_reboot_on_kernel_update: false

- hosts: hypervisors
  become: true
  gather_facts: false
  ignore_unreachable: false
  roles:
    - simoncaron.pve_addons

- hosts: vm
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - xterm_js

- hosts: docker
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - geerlingguy.docker
    - docker
    - dotfiles_copy

- hosts: nfs_clients
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - nfs_client
    - more_users

- hosts: workstations
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - arch_workstation
    - ssh_agent
    - dotfiles_clone

- hosts: apps
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - mariadb_backup

- hosts: dmz-apps
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - role: remote_logs
      vars:
        gelf_docker: true

- hosts: jj
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - dotfiles_copy
    - more_users
    - role: remote_logs
      vars:
        rsyslog_auth: true
        gelf_docker: false

- hosts: titania
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - arch_desktop
    - arch_secureboot

- hosts: fornax
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - arch_laptop
