---
- name: Prompt for a variable
  hosts: cepheus
  vars_prompt:
    - name: my_variable_prompt
      prompt: "Enter a value for my_variable"
      private: false  # Set to yes if the variable is sensitive
  tasks:
    - set_fact:
        my_variable: "{{ my_variable_prompt }}"
    - debug:
        msg: "Value of my_variable is {{ my_variable }}"

- name: Use the variable in another play
  hosts: localhost
  tasks:
    - debug:
        msg: "Value of my_variable in the second play is {{ hostvars['cepheus']['ansible_facts']['my_variable'] }}"
