---
# Do update pre-tasks before anything else...

- name: Run upgrades
  hosts: v3
  become: true
  gather_facts: true
  ignore_unreachable: true
  pre_tasks:
    - name: Update apt index
      tags: update, upgrade
      when: ansible_os_family == "Debian"
      changed_when: false
      apt:
        update_cache: true
    - name: Run apt dist upgrade
      tags: upgrade
      when: ansible_os_family == "Debian"
      apt:
        upgrade: dist
        autoremove: true
    - name: Update pacman index
      tags: update, upgrade
      changed_when: false
      when: ansible_os_family == "Archlinux"
      community.general.pacman:
        update_cache: true
    - name: Run pacman upgrade
      tags: upgrade
      when: ansible_os_family == "Archlinux"
      community.general.pacman:
        upgrade: true

# ...then run base config on all machines...

- name: Base config
  hosts: v3
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - base

# ...and finally, do role-specific tasks

- name: Roles
  hosts: lyra
  become: true
  gather_facts: false
  ignore_unreachable: false
  roles:
    - pve_networking
    - geerlingguy.ntp
    - role: lae.proxmox
      vars:
        pve_reboot_on_kernel_update: false
        pve_zfs_enabled: true
        pve_zfs_options: |-
          options zfs zfs_arc_max=8589934592
          options zfs zfs_arc_min=2147483648
    - role: artis3n.tailscale
      tags: tailscale
      vars:
        tailscale_args: --advertise-tags=tag:nfs-server

- name: Roles
  hosts: hypervisors
  become: true
  gather_facts: false
  ignore_unreachable: false
  roles:
    - simoncaron.pve_addons
    - apprise

- name: Roles
  hosts: vm
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - xterm_js
    - apprise

- name: Roles
  hosts: docker
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - geerlingguy.docker
    - docker
    - dotfiles_copy
    - role: artis3n.tailscale
      tags: tailscale
      vars:
        tailscale_args: --advertise-exit-node --advertise-tags=tag:docker

- name: Roles
  hosts: nfs_clients
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - nfs_client

- name: Roles
  hosts: offsite01
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - role: artis3n.tailscale
      tags: tailscale
      vars:
        tailscale_args: --advertise-tags=tag:offsite
    - dotfiles_copy

- name: Roles
  hosts: ixion
  become: true
  gather_facts: false
  ignore_unreachable: true
  roles:
    - arch_workstation
    - arch_laptop
    - arch_secureboot
    - dotfiles_clone
    - role: artis3n.tailscale
      tags: tailscale

- name: Host-specific tasks
  hosts: v3
  gather_facts: false
  become: true
  tasks:
    - name: Run host-specific tasks
      include_tasks:
        file: "{{ item }}"
      with_first_found:
        - files: host_tasks/{{ ansible_hostname }}.yml
          skip: true
