---
- name: Configure VyOS
  hosts: vyos
  tasks:
    - name: Ensure vyos and ansible passwords are locked
      tags: user, config
      vyos.vyos.vyos_config:
        lines:
          - delete system login user vyos authentication encrypted-password
          - delete system login user ansible authentication encrypted-password

    - name: Ensure user is present
      tags: user, config
      vyos.vyos.vyos_config:
        lines:
          - set system login user {{ user }} full-name {{ user }}
          - set system login user {{ user }} authentication public-keys Homelab_{{ user }} type ssh-ed25519
          - set system login user {{ user }} authentication public-keys Homelab_{{ user }} key {{ ssh_key | regex_search("AAAA.+?[^\S]") }}

    - name: Set post-login banner
      vyos.vyos.vyos_banner:
        banner: post-login
        text: Welcome to VyOS
        state: present

    - name: Configure interfaces
      vyos.vyos.vyos_interfaces:
        state: overridden
        config:
          - name: eth0
            enabled: true
            description: WAN
          - name: eth1
            enabled: true
            description: Internal
            vifs:
              - vlan_id: 10
                enabled: true
                description: Servers VLAN

    - name: Configure IP addresses/networks
      vyos.vyos.vyos_l3_interfaces:
        state: merged
        config:
          - name: eth1
            vifs:
              - vlan_id: 10
                ipv4:
                  - address: 10.69.10.1/24

    - name: Save configuration to boot config
      vyos_config:
        save: true
