---

- name: Configure users
  hosts: vyos
  tasks:
    - name: Ensure vyos and ansible passwords are locked
      tags: user, config
      vyos.vyos.vyos_config:
        lines:
          - delete system login user vyos authentication encrypted-password
          - delete system login user ansible authentication encrypted-password

    - name: Ensure user is present
      tags: user, config
      vyos.vyos.vyos_config:
        lines:
          - set system login user {{ user }} full-name {{ user }}
          - set system login user {{ user }} authentication public-keys Homelab_{{ user }} type ssh-ed25519
          - set system login user {{ user }} authentication public-keys Homelab_{{ user }} key {{ ssh_key | regex_search("AAAA.+?[^\S]") }}

    - name: Set post-login banner
      vyos.vyos.vyos_banner:
        banner: post-login
        text: Welcome to VyOS
        state: present
