- name: Create mountpoints
  tags: config, nfs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop: 
    - /ssd/app/games
    - /hdd/app/games
  register: mountpoints

- name: Make mountpoints immutable
  tags: config, nfs
  ansible.builtin.file:
    path: "{{ item }}"
    attributes: +i
  loop: 
    - /ssd/app/games
    - /hdd/app/games
  when: mountpoints.changed

- name: Map NFS shares
  tags: config, nfs
  blockinfile:
    path: /etc/fstab
    block: |
      10.0.0.5:/ssd/app/games	/ssd/app/games	nfs	auto	0	0
  register: nfs
  
- name: Mount network shares
  tags: config, nfs
  shell: mount -a
  when: nfs.changed

- name: Copy docker-compose.yml
  tags: docker, compose
  copy:
    src: docker-compose.yml
    dest: "{{ compose_dir }}"
    mode: 0664
    owner: root
    group: docker 

- name: Copy .env
  tags: docker, compose
  copy:
    src: .env
    dest: "{{ compose_dir }}"
    mode: 0440
    owner: root
    group: docker 

- name: Create and start services
  tags: docker, compose
  community.docker.docker_compose:
    project_src: "{{ compose_dir }}"
    remove_orphans: yes
  register: output