version: '3.7'


services:
  mc-survival-3:
    container_name: mc-survival-3
    image: itzg/minecraft-server:java17
    restart: unless-stopped

    ports:
      - 25568:25565

    volumes:
      - '/ssd/app/games/minecraft/mc-survival-211205-1.18.0:/data'

    environment:
      TZ: 'America/Chicago'
      EULA: 'True'
      PVP: 'false'
      DIFFICULTY: 'normal'
      SERVER_NAME: 'Haven Grotto'
      OPS: ${MINECRAFT_OP}
      MEMORY: '3G'
      MOTD: 'Haven Grotto'
      TYPE: 'FORGE'
      VERSION: '1.18.2'

  mc-survival-4:
    container_name: mc-survival-4
    image: itzg/minecraft-server:java17
    restart: unless-stopped

    ports:
      - 25569:25565

    volumes:
      - '/ssd/app/games/minecraft/mc-survival-221003-1.19.2:/data'

    environment:
      TZ: 'America/Chicago'
      EULA: 'True'
      PVP: 'false'
      DIFFICULTY: 'normal'
      SERVER_NAME: 'Boulder Keep'
      OPS: ${MINECRAFT_OP}
      MEMORY: '3G'
      MOTD: 'Boulder Keep'
      TYPE: 'FORGE'
      VERSION: '1.19.2'
      VIEW_DISTANCE: '24'

  factorio:
    container_name: factorio
    image: factoriotools/factorio:stable
    restart: unless-stopped
    
    ports:
      - 34197:34197/udp
      - 27015:27015/tcp

    volumes:
      - /ssd/app/games/factorio/loriini:/factorio

    environment:
      UPDATE_MODS_ON_START: 'false'
      SAVE_NAME: "Loriini"

  postgres:
    container_name: postgres
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hedgedoc
    restart: unless-stopped

  hedgedoc:
    image: lscr.io/linuxserver/hedgedoc:latest
    container_name: hedgedoc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - CMD_DOMAIN=hd.{{domain}}
      - CMD_URL_ADDPORT=true #optional
      - CMD_PROTOCOL_USESSL=false #optional
      - CMD_PORT=3000 #optional
      - CMD_ALLOW_ORIGIN=['hd.{{domain}}'] #optional
    ports:
      - 3000:3000
    restart: unless-stopped