---
networks:
  web:

services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome
    restart: unless-stopped

    volumes:
      - "{{ app_root }}/adguard/config:/opt/adguardhome/conf"
      - "{{ app_root }}/adguard/data:/opt/adguardhome/work"

    ports:
      - {{ tailscale_web01_ip }}:53:53/udp

    networks:
      - web

    labels:
      traefik.enable: true
      traefik.http.routers.adguard.rule: Host(`ads.{{ tertiary_domain }}`)
      traefik.http.routers.adguard.entrypoints: https
      traefik.http.routers.adguard.tls.certresolver: default
      traefik.http.services.adguard.loadbalancer.server.port: 3000
      traefik.http.routers.adguard.middlewares: authelia

    