networks:
  web:
  ldap:
  redis:

services:
  lldap:
    container_name: lldap
    image: lldap/lldap:stable
    restart: unless-stopped

    networks:
      web:
      ldap:

    env_file: keycloak.env
    environment:
      # - UID=####
      # - GID=####
      TZ: {{ timezone }}

    volumes:
      - "{{ app_root }}/lldap:/data"

    labels:
      traefik.enable: true
      traefik.http.routers.ldap.rule: Host(`usermgmt.{{ tertiary_domain }}`)
      traefik.http.routers.ldap.entrypoints: https
      traefik.http.routers.ldap.tls.certresolver: default
      traefik.http.services.ldap.loadbalancer.server.port: 17170

  authelia:
    container_name: authelia
    image: ghcr.io/authelia/authelia:master
    restart: unless-stopped

    depends_on:
      - lldap

    networks:
      web:
      ldap: 
      redis:

    environment:
      # AUTHELIA_JWT_SECRET_FILE: /secrets/jwt_secret
      AUTHELIA_SESSION_SECRET_FILE: /secrets/session_secret
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/storage_key
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /secrets/smtp_pass
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: /secrets/ldap_pass
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE: /secrets/oidc_key
      # AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: /secrets/oidc_hmac_secret

    volumes:
      - "{{ app_root }}/authelia/config:/config"
      - "{{ app_root }}/authelia/secrets:/secrets"

    healthcheck:
      interval: 4s
      start_period: 30s

    labels:
      traefik.enable: true
      traefik.docker.network: doc_web
      traefik.http.routers.auth.rule: Host(`login.{{ tertiary_domain }}`)
      traefik.http.routers.auth.entrypoints: https
      traefik.http.routers.auth.tls.certresolver: default
      traefik.http.services.auth.loadbalancer.server.port: 9091
      traefik.http.middlewares.authelia.forwardAuth.address: http://authelia:9091/api/verify?rd=https%3A%2F%2Fauth.{{ tertiary_domain }}%2F
      traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader: true
      traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders: Remote-User,Remote-Groups,Remote-Name,Remote-Email
      # traefik.http.middlewares.authelia-basic.forwardAuth.address: http://authelia:9091/api/verify?auth=basic
      # traefik.http.middlewares.authelia-basic.forwardAuth.trustForwardHeader: true
      # traefik.http.middlewares.authelia-basic.forwardAuth.authResponseHeaders: Remote-User,Remote-Groups,Remote-Name,Remote-Email


  authelia_redis:
    container_name: authelia_redis
    image: redis:alpine
    restart: unless-stopped

    networks:
      redis:

    volumes:
      - "{{ app_root }}/authelia/redis:/data"
    environment:
      TZ: {{ timezone }}