networks:
  web:

services:
  cryptpad:
    container_name: cryptpad
    # No 'latest' tag published
    image: cryptpad/cryptpad:version-2024.3.0
    restart: unless-stopped

    environment:
      CPAD_MAIN_DOMAIN: https://docs.{{ tertiary_domain }}
      CPAD_SANDBOX_DOMAIN: https://docs-ui.{{ tertiary_domain }}
      CPAD_CONF: /cryptpad/config/config.js
      CPAD_INSTALL_ONLYOFFICE: "yes"

    networks:
      - web

    volumes:
      - /opt/cryptpad/blob:/cryptpad/blob
      - /opt/cryptpad/block:/cryptpad/block
      - /opt/cryptpad/customize:/cryptpad/customize
      - /opt/cryptpad/data:/cryptpad/data
      - /opt/cryptpad/files:/cryptpad/datastore
      - /opt/cryptpad/config/config.js:/cryptpad/config/config.js:ro
      - /opt/cryptpad/onlyoffice/dist:/cryptpad/www/common/onlyoffice/dist
      - /opt/cryptpad/onlyoffice/conf:/cryptpad/onlyoffice-conf

    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000

    healthcheck:
      interval: 4s
      start_period: 30s

    labels:
      traefik.enable: true
      traefik.http.routers.docs.rule: Host(`docs.{{ tertiary_domain }}`) ||  Host(`docs-ui.{{ tertiary_domain }}`)
      traefik.http.routers.docs.tls.certresolver: default
      traefik.http.services.docs.loadbalancer.server.port: 3000