---
networks:
  web: 
  db:
  redis:

services:
  mastodon:
    # Version locked bc nightly builds from glitch
    image: linuxserver/mastodon:4.2.10
    container_name: mastodon
    restart: unless-stopped

    # Pegs the CPUs on startup, so limit it so it can't peg both
    deploy:
      resources:
        limits:
          cpus: '1.2'

    env_file:
      - mastodon.env

    environment:
      PUID: 5001
      PGID: 5001
      TZ: {{ timezone }}
    
    networks:
      web:
      db:
      redis:

    volumes:
      - "{{ app_root }}/mastodon/config:/config"

    labels:
      traefik.enable: true
      traefik.http.routers.social.rule: Host(`social.{{ tertiary_domain }}`)
      traefik.http.routers.social.entrypoints: https
      traefik.http.routers.social.tls.certresolver: default
      traefik.http.services.social.loadbalancer.server.port: 80
      # Breaks apps
      # traefik.http.routers.social.middlewares: authelia


  mastodon_postgres:
    container_name: mastodon_postgres
    image: postgres:16
    user: 5001:5001
    restart: unless-stopped
    env_file:
      - mastodon.env
    volumes:
      - "/{{ app_root }}/mastodon/db:/var/lib/postgresql/data"
    networks:
      db:

  mastodon_redis:
    container_name: mastodon_redis
    image: redis:alpine
    user: 5001:5001
    restart: unless-stopped

    networks:
      redis:

    volumes:
      - "{{ app_root }}/mastodon/redis:/data"
    environment:
      TZ: {{ timezone }}