networks:
  web:
  peertube_db:

services:
  peertube:
    container_name: peertube
    image: chocobozzz/peertube:production-bookworm
    restart: unless-stopped
    env_file:
      - peertube.env
    volumes:
      - assets:/app/client/dist
      - /opt/peertube/data:/data
      - /opt/peertube/config:/config
    networks:
      web:
      peertube_db:
    depends_on:
      - peertube_postgres
      - peertube_redis
    labels:
      traefik.enable: true
      traefik.http.routers.vid.rule: Host(`v.{{ tertiary_domain }}`)
      traefik.http.routers.vid.tls.certresolver: default
      traefik.http.services.vid.loadbalancer.server.port: 9000

  peertube_postgres:
    container_name: peertube_postgres
    image: postgres:13-alpine
    restart: unless-stopped
    env_file:
      - peertube.env
    volumes:
      - /opt/peertube/db:/var/lib/postgresql/data
    networks:
      peertube_db:
    labels:
      traefik.enable: false


  peertube_redis:
    container_name: peertube_redis
    image: redis:6-alpine
    restart: unless-stopped
    volumes:
      - /opt/peertube/redis:/data
    networks:
      peertube_db:
    labels:
      traefik.enable: false

volumes:
  assets:
