networks: 
  web:

services:
  tmodloader:
    image: jacobsmile/tmodloader1.4:latest
    container_name: tmodloader
    restart: unless-stopped

    ports:
      - "7777:7777"
    expose:
      - "7777"
    
    environment:
      # Download and enable the Calamity mod and CalamityMusic mod.
      TMOD_AUTODOWNLOAD: 2824688072,2824688266
      TMOD_ENABLEDMODS: 2824688072,2824688266
      TMOD_SHUTDOWN_MESSAGE: yeet
      TMOD_AUTOSAVE_INTERVAL: 15
      TMOD_MOTD: Welcome to The Paradise of Mangos!
      TMOD_MAXPLAYERS: 8
      TMOD_WORLDNAME: The Paradise of Mangos
      UPDATE_NOTICE: false
    
    env_file:
      - terraria.env

    volumes:
      - "{{ app_root }}/terraria/2501_paradise_of_mangos:/data"

    labels:
      traefik.enable: false