networks:
  web:

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped

    networks:
      web:

    environment:
      DOMAIN: "https://vault.{{ tertiary_domain }}" 
      SIGNUPS_ALLOWED: false

    volumes:
      - /opt/vaultwarden:/data

    labels:
      traefik.enable: true
      traefik.http.routers.vault.rule: Host(`vault.{{ tertiary_domain }}`)
      traefik.http.routers.vault.entrypoints: https
      traefik.http.routers.vault.tls.certresolver: default
      traefik.http.services.vault.loadbalancer.server.port: 80