---
networks:
  web:

services:
  vikunja:
    container_name: vikunja
    image: vikunja/vikunja
    restart: unless-stopped

    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://tasks.{{ tertiary_domain }}
      VIKUNJA_DATABASE_PATH: /db/vikunja.db
      VIKUNJA_SERVICE_ENABLEREGISTRATION: false
    
    volumes:
      - "{{ app_root }}/vikunja/files:/app/vikunja/files"
      - "{{ app_root }}/vikunja/db:/db"
    
    networks:
      web:
    
    labels:
      traefik.enable: true
      traefik.http.routers.tasks.rule: Host(`tasks.{{ tertiary_domain }}`)
      traefik.http.routers.tasks.entrypoints: https
      traefik.http.routers.tasks.tls.certresolver: default
      traefik.http.services.tasks.loadbalancer.server.port: 3456
