---
- name: Enable remote syslogging for auth events
  tags: config, logging
  when: rsyslog_auth | default(false)
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: "@@10\\.0\\."
    line: authpriv.* @@10.0.0.5:514;RSYSLOG_SyslogProtocol23Format

- name: Enable Docker GELF logs
  tags: config, logging, docker
  when: gelf_docker | default(false)
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0600"
  notify: Restart Docker daemon
