#TODO: Select dots to copy based on installed packages

- name: Copy selected dots
  tags: config, dots
  copy:
    # Depends on dotfiles being symlinked at the `files` directory
    # ln -s ~/.dotfiles roles/dotfiles_copy/files
    src:  "{{ item.src }}"
    dest: "/home/{{ user }}/{{ item.dst }}"
    force: yes
  with_items:
    - { src: "vim/vimrc", dst: ".vimrc" }
    # - { src: "i3", dst: ".config/i3" }
    # - { src: "i3status", dst: ".config/i3status" }
    # - { src: "kitty", dst: ".config/kitty" }
    # - { src: "zsh/zshrc.local", dst: ".zshrc.local" }

- name: Copy selected dots to root
  tags: config, dots
  copy:
    src:  "{{ item.src }}"
    dest: "/root/{{ item.dst }}"
    force: yes
  with_items:
    - { src: "vim/vimrc", dst: ".vimrc" }