---
- name: Install bridge-utils
  apt:
    name: bridge-utils

- name: Configure /etc/network/interfaces
  tags: config, net
  template:
    src: "{{ inventory_hostname }}/pve_networking/interfaces.j2"
    dest: /etc/network/interfaces
    mode: "0644"
  notify: Reload network interfaces

- name: Configure /etc/resolv.conf
  tags: config, net
  template:
    src: "{{ inventory_hostname }}/pve_networking/resolv.conf.j2"
    dest: /etc/resolv.conf
    mode: "0644"
  notify: Reload network interfaces
