---
- name: Install bridge-utils
  apt:
    name: bridge-utils

- name: Configure /etc/network/interfaces
  template:
    src: "{{ interfaces_template }}"
    dest: /etc/network/interfaces
    mode: "0644"
  notify: Reload network interfaces

- name: Configure /etc/resolv.conf
  template:
    src: "{{ resolv_template }}"
    dest: /etc/resolv.conf
    mode: "0644"
  notify: Reload network interfaces
