#!/bin/bash

url=https://hc-ping.com/{{ backblaze_healthcheck_id }}

# Kick the healthchecks.io monitor
curl -fsS --retry 3 $url/start > /dev/null

# Save error codes so we know whether any command failed
error=0

# Move to config directory
cd ~/.config/backblaze;

{% if 'docker' in group_names %}
/usr/local/bin/docker-compose $(find /opt/doc/*.yml | sed -e "s/^/-f /") stop
{% endif %}

for dir in {{ backblaze_include_dirs }}
do
  echo Backing up $dir...
  rclone sync --fast-list --transfers 32 --exclude-from excludes.conf --create-empty-src-dirs $dir b2-crypt:$dir
  # Sets error to greater of current value and new value
  error=$(( $? > $error ? $? : $error))
done

# Explicitly fail if any command failed

if [[ $error -ne 0 ]] ; then
  echo At least one item failed.
  url=$url/fail
fi

{% if 'docker' in group_names %}
/usr/local/bin/docker-compose $(find /opt/doc/*.yml | sed -e "s/^/-f /") start
{% endif %}

# Confirm the finish with healthchecks.io
curl -fsS --retry 3 $url > /dev/null
