#!/bin/bash

url=https://hc-ping.com/{{ healthcheck_id_backblaze }}

# Kick the healthchecks.io monitor
curl -fsS --retry 3 $url/start > /dev/null

# Save error codes so we know whether any command failed
error=0

# Sync with Backblaze - takes each path in includes.conf and uploads it
# with the same path to Backblaze

# Move to config directory
cd ~/.config/backblaze;

for dir in /ssd/app/ /hdd/enc/app/
do
  echo Backing up $dir...
  rclone sync --fast-list --transfers 32 --exclude-from excludes.conf --create-empty-src-dirs $dir b2-crypt:$dir
  # Sets error to greater of current value and new value
  error=$(( $? > $error ? $? : $error))
done

# Explicitly fail if any command failed

if [[ $error -ne 0 ]] ; then
  echo At least one item failed.
  url=$url/fail
fi

# Confirm the finish with healthchecks.io
curl -fsS --retry 3 $url > /dev/null
