---
# Creates a user-level systemd service for the SSH agent
# Configures pam_env with the SSH_AUTH_SOCK path for all users

- name: Create user systemd directory
  tags: config, ssh
  file:
    path: /home/{{ user }}/.config/systemd/user/
    state: directory
    mode: 0770
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Create ssh agent user service
  tags: config, ssh
  copy:
    src: ssh-agent.service
    dest: /home/{{ user }}/.config/systemd/user/ssh-agent.service
    mode: 0660
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Enable and start ssh agent
  tags: config, ssh
  become: true
  become_user: "{{ user }}"
  systemd:
    name: ssh-agent
    scope: user
    daemon_reload: true
    state: started
    enabled: true

- name: Configure pam_env with SSH agent path
  tags: config, ssh
  blockinfile:
    dest: /etc/security/pam_env.conf
    mode: 0600
    create: true
    block: |
      # Set SSH_AUTH_SOCK so SSH agent can be found
      SSH_AUTH_SOCK DEFAULT="${XDG_RUNTIME_DIR}/ssh-agent.socket"
