---
- name: Enable SSH agent forwarding with sudo
  tags: config, dots
  lineinfile:
    dest: /etc/sudoers
    insertafter: ^#?\s*Defaults\s+env_keep\b
    line: Defaults    env_keep += "SSH_AUTH_SOCK"

# Needed so that our user can access the SSH agent, using credentials passed
# from the ansible control host to authenticate to the git repo
- name: Change SSH agent socket owner to {{ user }}
  tags: config, dots, dotclone
  changed_when: false # no way to distinguish changed/unchanged
  command:
    cmd: bash -c 'chown -R {{ user }} /tmp/ssh-XXXX*'

- name: Clone dotfiles
  tags: config, dots, dotclone
  become: true
  become_user: "{{ user }}"
  git:
    repo: ssh://git@gt.{{ domain }}:1108/subract/dotfiles.git
    dest: /home/{{ user }}/.dotfiles

- name: Revert SSH agent socket owner
  tags: dotclone
  changed_when: false # no way to distinguish changed/unchanged
  command:
    cmd: bash -c 'chown -R root /tmp/ssh-XXXX*'

- name: Create user systemd directory
  tags: config, dots
  file:
    path: ~/.config/systemd/user/default.target.wants
    state: directory
    mode: 0660
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Symlink dots
  tags: config, dots
  become: true
  become_user: "{{ user }}"
  file:
    src: /home/{{ user }}/.dotfiles/{{ item.src }}
    dest: /home/{{ user }}/{{ item.dst }}
    state: link
    force: true
  with_items:
    - { src: bat, dst: .config/bat }
    - { src: dunst, dst: .config/dunst }
    - { src: gtk-3.0, dst: .config/gtk-3.0 }
    - { src: i3, dst: .config/i3 }
    - { src: icons, dst: .icons }
    - { src: kitty, dst: .config/kitty }
    - { src: polybar, dst: .config/polybar }
    - { src: redshift, dst: .config/redshift }
    - { src: vim/vimrc, dst: .vimrc }
    - { src: xfce4, dst: .config/xfce4 }
    - { src: zsh/zshrc.local, dst: .zshrc.local }
    # The following creates and enables an SSH agent
    - { src: ssh-agent/ssh-agent.service, dst: .config/systemd/user/default.target.wants/ssh-agent.service }
    - { src: ssh-agent/ssh-agent.service, dst: .config/systemd/user/ssh-agent.service }
    - { src: ssh-agent/pam_env.conf, dst: /etc/security/pam_env.conf }

- name: Rebuild bat theme cache
  tags: config, dots
  changed_when: false
  become: true
  become_user: "{{ user }}"
  command:
    cmd: bat cache --build
