---
- name: Clone dotfiles
  tags: config, dots, dotclone
  become: true
  become_user: "{{ user }}"
  git:
    repo: https://gt.{{ primary_domain }}/subract/dotfiles.git # noqa latest
    dest: /home/{{ user }}/.dotfiles

- name: Symlink dots
  tags: config, dots
  become: true
  become_user: "{{ user }}"
  file:
    src: /home/{{ user }}/.dotfiles/{{ item.src }}
    dest: /home/{{ user }}/{{ item.dst }}
    state: link
    force: true
  with_items:
    - { src: bat, dst: .config/bat }
    - { src: dunst, dst: .config/dunst }
    - { src: i3, dst: .config/i3 }
    - { src: icons, dst: .icons }
    - { src: kitty, dst: .config/kitty }
    - { src: polybar, dst: .config/polybar }
    - { src: redshift, dst: .config/redshift }
    - { src: vim/vimrc, dst: .vimrc }
    - { src: xfce4, dst: .config/xfce4 }
    - { src: zsh/zshrc.local, dst: .zshrc.local }

- name: Rebuild bat theme cache
  tags: config, dots
  changed_when: false
  become: true
  become_user: "{{ user }}"
  command:
    cmd: bat cache --build
