- name: Clone dotfiles
  tags: config, dots
  become: yes
  become_user: "{{ user }}"
  git:
    repo: https://gt.{{ domain }}/subract/dotfiles.git
    dest: "/home/{{ user }}/.dotfiles"


- name: Create user systemd directory
  tags: config, dots
  become: yes
  become_user: "{{ user }}"
  file:
    path: "~/.config/systemd/user/default.target.wants"
    state: directory

- name: Symlink dots
  tags: config, dots
  become: yes
  become_user: "{{ user }}"
  file:
    src:  "/home/{{ user }}/.dotfiles/{{ item.src }}"
    dest: "/home/{{ user }}/{{ item.dst }}"
    state: link
    force: yes
  with_items:
    - { src: "vim/vimrc", dst: ".vimrc" }
    - { src: "i3", dst: ".config/i3" }
    - { src: "i3status", dst: ".config/i3status" }
    - { src: "kitty", dst: ".config/kitty" }
    - { src: "redshift", dst: ".config/redshift" }
    - { src: "zsh/zshrc.local", dst: ".zshrc.local" }
    # The following creates and enables an SSH agent
    - { 
        src: "ssh-agent/ssh-agent.service", 
        dst: ".config/systemd/user/default.target.wants/ssh-agent.service" 
      }
    - { 
        src: "ssh-agent/ssh-agent.service", 
        dst: ".config/systemd/user/ssh-agent.service" 
      }
    - { src: "ssh-agent/.pam_environment", dst: ".pam_environment" }

