- name: Clone dotfiles
  tags: config, dots
  become: yes
  become_user: "{{ user }}"
  git:
    repo: https://gl.<redacted>/<redacted>/dotfiles.git
    dest: "/home/{{ user }}/.dotfiles"
  register: dotfiles

- name: Generate i3 config
  tags: config, dots
  become: yes
  become_user: "{{ user }}"
  command: "j4-make-config -r -a {{ workstation_class }} purple"
  when: dotfiles.changed

- name: Symlink dots
  tags: config, dots
  become: yes
  become_user: "{{ user }}"
  file:
    src:  "/home/{{ user }}/.dotfiles/{{ item.src }}"
    dest: "/home/{{ user }}/{{ item.dst }}"
    state: link
    force: yes
  with_items:
    - { src: "vim/vimrc", dst: ".vimrc" }
    - { src: "i3", dst: ".config/i3" }
    - { src: "i3status", dst: ".config/i3status" }
    - { src: "kitty", dst: ".config/kitty" }
    - { src: "zsh/zshrc.local", dst: ".zshrc.local" }

