---
- name: Install preloader-signed
  tags: pkg, aur, secureboot
  become: false
  kewlfft.aur.aur:
    name: preloader-signed
    state: present
  register: preloader

- name: Configure refind to use preloader-signed
  tags: secureboot
  command:
    cmd: refind-install --preloader /usr/share/preloader-signed/PreLoader.efi --yes
  when: preloader.changed
