version: "3.7"

networks:
  web:
  changedetection:

services:
  changedetection:
    container_name: changedetection
    image: ghcr.io/dgtlmoon/changedetection.io
    restart: unless-stopped

    networks:
      - web
      - changedetection

    environment:
      BASE_URL: https://change.{{ tertiary_domain }}/
      USE_X_SETTINGS: 1
      # HIDE_REFERER: true
      # LOGGER_LEVEL: DEBUG
      PLAYWRIGHT_DRIVER_URL: ws://playwright-chrome:3000/?stealth=1

    depends_on:
      playwright-chrome:
        condition: service_started

    volumes:
      - {{ app_root }}/changedetction:/datastore

    labels:
      traefik.enable: true
      traefik.http.routers.change.rule: Host(`change.{{ tertiary_domain }}`)
      traefik.http.routers.change.entrypoints: https
      traefik.http.routers.change.tls.certresolver: default
      traefik.http.services.change.loadbalancer.server.port: 5000
      traefik.http.routers.change.middlewares: authelia

  playwright-chrome:
    container_name: playwright-chrome
    image: browserless/chrome:1.60-chrome-stable
    restart: unless-stopped

    networks:
      - changedetection

    environment:
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1024
      SCREEN_DEPTH: 16
      ENABLE_DEBUGGER: false
      PREBOOT_CHROME: true
      CONNECTION_TIMEOUT: 300000
      MAX_CONCURRENT_SESSIONS: 10
      CHROME_REFRESH_TIME: 600000
      DEFAULT_BLOCK_ADS: true
      DEFAULT_STEALTH: true