version: "3.7"

networks:
  web:
  db:

services:
  cyberchef:
    container_name: cyberchef
    image: mpepping/cyberchef
    restart: unless-stopped

    networks:
      - web

    environment:
      TZ: {{ timezone }}

    labels:
      traefik.enable: true
      traefik.http.routers.chef.rule: Host(`chef.{{ tertiary_domain }}`)
      traefik.http.routers.chef.entrypoints: https
      traefik.http.routers.chef.tls.certresolver: default
      traefik.http.services.chef.loadbalancer.server.port: 8000
      homepage.group: Apps
      homepage.name: Swiss army knife
      homepage.icon: cyberchef.png
      homepage.href: https://chef.{{ tertiary_domain }}/
      homepage.description: CyberChef
      homepage.siteMonitor: http://cyberchef:8000
      homepage.weight: 60