version: "3.7"

networks:
  web:
  docker-socket:

services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped

    networks:
      - web
      - docker-socket

    environment:
      LOG_LEVEL: debug

    volumes:
      - "{{ app_root }}/homepage/config:/app/config"
      - "{{ app_root }}/homepage/icons:/app/public/icons"

    healthcheck:
      interval: 4s
      start_period: 30s

    labels:
      traefik.enable: true
      traefik.http.routers.dash.rule: Host(`dash.{{ tertiary_domain }}`)
      traefik.http.routers.dash.entrypoints: https
      traefik.http.routers.dash.tls.certresolver: default
      traefik.http.services.dash.loadbalancer.server.port: 3000
      traefik.http.routers.dash.middlewares: authelia