version: "3.7"

networks:
  web:
  mqtt:
  db:

services:
  home_assistant:
    container_name: home_assistant
    image: homeassistant/home-assistant:latest
    restart: unless-stopped

    networks:
      - web
      - mqtt
      - db

    environment:
      TZ: {{ timezone }}

    volumes:
      - {{ app_root }}/home_assistant_neo:/config

    # ports:
    #   - 1400:1400
    #   - 21064:21064 # HomeKit

    labels:
      traefik.enable: true
      traefik.http.routers.home.rule: Host(`home.{{ tertiary_domain }}`)
      traefik.http.routers.home.entrypoints: https
      traefik.http.routers.home.tls.certresolver: default
      traefik.http.services.home.loadbalancer.server.port: 8123

  # mosquitto:
  #   container_name: mosquitto
  #   image: eclipse-mosquitto
  #   restart: unless-stopped

  #   networks:
  #     - mqtt

  #   volumes:
  #     - {{ app_root }}/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  #   labels:
  #     - traefik.enable=false

  # zigbee2mqtt:
  #   container_name: zigbee2mqtt
  #   image: koenkk/zigbee2mqtt

  #   depends_on:
  #     - mosquitto

  #   volumes:
  #     - {{ app_root }}/zigbee2mqtt:/app/data

  #   devices:
  #     - /dev/ttyUSB0

  #   networks:
  #     - web
  #     - mqtt

  #   environment:
  #     TZ: {{ timezone }}

  #   labels:
  #     traefik.enable: true
  #     traefik.http.routers.zigbee.rule: Host(`zigbee.{{ tertiary_domain }}`)
  #     traefik.http.routers.zigbee.entrypoints: https
  #     traefik.http.routers.zigbee.tls.certresolver: default
  #     traefik.http.services.zigbee.loadbalancer.server.port: 8080