version: '3.7'

networks:
  web:

services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: monitor
    restart: unless-stopped

    # Netdata needs to be able to listen for TCP traffic
    # to receive data from children
    ports:
      - 19999:19999

    networks:
      - web

    environment:
      DISABLE_TELEMETRY: 1

    volumes:
     - "{{ app_root }}/netdata/config:/etc/netdata"
     - "{{ app_root }}/netdata/lib:/etc/netdata"
     - "{{ app_root }}/netdata/cache:/etc/netdata"

    healthcheck:
      interval: 4s
      start_period: 30s

    labels:
      traefik.enable: true
      traefik.http.routers.monitor.rule: Host(`monitor.{{ tertiary_domain }}`)
      traefik.http.routers.monitor.entrypoints: https
      traefik.http.routers.monitor.tls.certresolver: default
      traefik.http.services.monitor.loadbalancer.server.port: 19999
      traefik.http.routers.monitor.middlewares: authelia
      homepage.group: Admin
      homepage.name: Monitoring
      homepage.icon: netdata.png
      homepage.href: https://monitor.{{ tertiary_domain }}/
      homepage.weight: 5
      homepage.description: Netdata
      homepage.siteMonitor: http://netdata:19999
      homepage.widget.type: netdata
      homepage.widget.url: http://netdata:19999

# volumes:
#   netdataconfig:
#   netdatalib:
#   netdatacache: