version: "3.7"

networks:
  web:
  db:

services:
  nextcloud:
    container_name: nextcloud
    image: linuxserver/nextcloud:latest
    restart: unless-stopped
    depends_on: 
      - nextcloud_mariadb

    volumes:
      - {{ app_root }}/nextcloud/config:/config
      - {{ app_root }}/nextcloud/data:/data

    environment:
      - PUID=1001
      - PGID=1001

    networks:
      - web
      - db

    labels:
      traefik.enable: true
      traefik.http.routers.file.rule: Host(`file.{{ tertiary_domain }}`)
      traefik.http.routers.file.entrypoints: https
      traefik.http.routers.file.tls.certresolver: default
      traefik.serversTransport.forwardingTimeouts.dialTimeout: 0s
      traefik.http.services.file.loadbalancer.server.port: 80
      homepage.group: Apps
      homepage.name: File sync
      homepage.icon: nextcloud.png
      homepage.href: https://file.{{ tertiary_domain }}/
      homepage.weight: 20
      homepage.description: Nextcloud
      homepage.siteMonitor: http://nextcloud
      homepage.widget.type: nextcloud
      homepage.widget.fields: '["freespace", "numfiles"]'
      homepage.widget.url: https://file.{{ tertiary_domain }}
      homepage.widget.key: ${NEXTCLOUD_API_KEY}


  nextcloud_mariadb:
    container_name: nextcloud_mariadb
    image: mariadb:latest
    restart: unless-stopped
    env_file: 
      - nextcloud.env

    volumes:
      - {{ app_root }}/nextcloud_mariadb/data:/var/lib/mysql

    networks:
      - db