- name: Add more sudo users
  tags: users, config
  user:
    name: "{{ item.name }}"
    group: sudo
  loop: "{{ users }}"

- name: Set user authorized keys
  tags: users, config
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.key }}"
  loop: "{{ users }}"