---
- name: Make mountpoints immutable
  tags: config, nfs
  ansible.builtin.file:
    path: "{{ item.path }}"
    attributes: +i
  loop: "{{ nfs_dirs }}"

- name: Reload systemd
  systemd:
    daemon_reload: true
