version: "3.7"

networks:
  web:
  mqtt:
  db:

services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    restart: unless-stopped

    volumes:
      - /ssd/app/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro

    networks:
      - web
      - mqtt
      - db

    ports:
      - 1400:1400
      - 21064:21064 # HomeKit

    labels:
      - traefik.enable=true
      - traefik.http.routers.ha.rule=Host(`ha.{{ domain }}`)
      - traefik.http.routers.ha.entrypoints=https
      - traefik.http.routers.ha.tls.certresolver=default
      - traefik.http.services.ha.loadbalancer.server.port=8123


  nodered:
    container_name: nodered
    image: nodered/node-red
    restart: unless-stopped
    user: root

    volumes:
      - /ssd/app/nodered:/data
      - /etc/localtime:/etc/localtime:ro

    networks:
      - web
      - mqtt

    environment:
      - TZ={{ timezone }}

    labels:
      - traefik.enable=true
      - traefik.http.routers.nr.rule=Host(`nr.{{ domain }}`)
      - traefik.http.routers.nr.entrypoints=https
      - traefik.http.routers.nr.tls.certresolver=default
      - traefik.http.services.nr.loadbalancer.server.port=1880


  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped

    networks:
      - mqtt

    volumes:
      - /ssd/app/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

    labels:
      - traefik.enable=false


  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    depends_on:
      - mosquitto

    volumes:
      - /ssd/app/zigbee2mqtt:/app/data

    devices:
      - /dev/ttyUSB0

    networks:
      - web
      - mqtt

    environment:
      - TZ={{ timezone }}

    labels:
      - traefik.enable=true
      - traefik.http.routers.zb.rule=Host(`zb.{{ domain }}`)
      - traefik.http.routers.zb.entrypoints=https
      - traefik.http.routers.zb.tls.certresolver=default
      - traefik.http.services.zb.loadbalancer.server.port=8080


  octoprint:
    container_name: octoprint
    image: octoprint/octoprint
    restart: unless-stopped

    devices:
     - /dev/ttyACM0:/dev/ttyACM0
     - /dev/video0:/dev/video0
    
    volumes:
    - /ssd/app/octoprint:/octoprint

    networks:
      - web

    environment:
      - ENABLE_MJPG_STREAMER=true

    labels:
      - traefik.enable=true
      - traefik.http.routers.op.rule=Host(`op.{{ domain }}`)
      - traefik.http.routers.op.entrypoints=https
      - traefik.http.routers.op.tls.certresolver=default
      - traefik.http.services.op.loadbalancer.server.port=80
