version: "3.8"

networks:
  immich:
  web:

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start-server.sh"]
    volumes:
      - ${IMMICH_DATA_LOCATION}:/usr/src/app/upload
      - ${IMMICH_AVEN_UPLOAD_LOCATION}:/usr/src/app/upload/library/aven
      - ${IMMICH_IMPORT_LOCATION}:/mnt/aven:ro
    env_file:
      - immich.env
    depends_on:
      - redis
      - database
    networks:
      immich:
      web:
    restart: unless-stopped

    labels:
      - traefik.enable=true
      - traefik.http.routers.im.rule=Host(`im.{{ primary_domain }}`)
      - traefik.http.routers.im.entrypoints=https
      - traefik.http.routers.im.tls.certresolver=default
      - traefik.http.services.im.loadbalancer.server.port=3001

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start-microservices.sh"]
    volumes:
      - ${IMMICH_DATA_LOCATION}:/usr/src/app/upload
      - ${IMMICH_AVEN_UPLOAD_LOCATION}:/usr/src/app/upload/library/aven
      - ${IMMICH_IMPORT_LOCATION}:/mnt/aven:ro
    env_file:
      - immich.env
    depends_on:
      - redis
      - database
    networks:
      immich:
    restart: unless-stopped


  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${IMMICH_DATA_LOCATION}:/usr/src/app/upload
      - ${IMMICH_AVEN_UPLOAD_LOCATION}:/usr/src/app/upload/library/aven
      - ${IMMICH_IMPORT_LOCATION}:/mnt/aven:ro
      - /ssd/app/immich/ml_cache:/cache
    env_file:
      - immich.env
    networks:
      immich:
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: unless-stopped
    networks:
      immich:


  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11

    env_file:
      - immich.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    networks:
      immich:
    volumes:
      - /ssd/app/immich/postgres:/var/lib/postgresql/data
    restart: unless-stopped
