version: "3.7"

services:
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    restart: unless-stopped

    environment:
      - PUID=1001
      - PGID=1001
      - TZ={{ timezone }}
      - DELUGE_LOGLEVEL=error #optional

    volumes:
      - /ssd/app/deluge/config:/config
      - /ssd/app/deluge/downloads:/downloads

    ports:
      - 80:8112
      - 6881:6881
      - 6881:6881/udp
