- name: Make user member of docker group
  tags: docker, config
  user:
    name: "{{ user }}"
    groups: docker
    append: yes

- name: Set docker env vars/shortcuts
  tags: docker, config
  blockinfile:
    path: "/home/{{ user }}/.zshenv"
    create: yes
    block: |
      export COMPOSE_FILE={{ compose_dir }}docker-compose.yml
      alias dc="docker-compose --project-directory {{ compose_dir }}"
      alias dcls="docker container ls"
      alias dcl="docker logs"
      alias dclf="docker logs --follow"

- name: Install pip3 and nfs-common
  tags: docker, sdk, nfs
  apt:
    name: 
      - python3-pip
      - nfs-common

- name: Install docker and docker-compose Python modules
  tags: docker, sdk
  pip:
    name: 
    - docker
    - docker-compose

- name: Create mountpoints
  tags: config, nfs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop: "{{ nfs_dirs }}"
  register: mountpoints

- name: Make mountpoints immutable
  tags: config, nfs
  ansible.builtin.file:
    path: "{{ item }}"
    attributes: +i
  loop: "{{ nfs_dirs }}"
  when: mountpoints.changed

- name: Map NFS shares
  tags: config, nfs
  lineinfile:
    path: /etc/fstab
    regexp: "{{ item }}"
    line: 10.0.0.5:{{ item }}	{{ item }}	nfs	auto	0	0
  loop: "{{ nfs_dirs }}"
  register: nfs
  

- name: Copy docker-compose.yml
  tags: docker, compose
  copy:
    src: "{{ compose_file }}"
    dest: "{{ compose_dir }}docker-compose.yml"
    mode: 0664
    owner: root
    group: docker 

- name: Copy .env
  tags: docker, env
  copy:
    src: "{{ env_file }}"
    dest: "{{ compose_dir }}.env"
    mode: 0440
    owner: root
    group: docker 

- name: Pull and start services
  tags: docker, compose, update
  community.docker.docker_compose:
    project_src: "{{ compose_dir }}"
    pull: yes
    remove_orphans: yes
  register: output

- name: Prune everything
  tags: docker, compose, update
  community.docker.docker_prune:
    containers: yes
    images: yes
    networks: yes
    volumes: yes
    builder_cache: yes