---
- name: Set docker env vars/shortcuts
  tags: docker, config
  blockinfile:
    path: /etc/zsh/zshrc.local
    create: true
    mode: "0644"
    owner: root
    group: root
    block: |
      alias dc='docker-compose $(find /opt/doc/*.yml | sed -e "s/^/-f /")'
      alias dcls="docker container ls"
      alias dcps="docker container ps"
      alias dcl="docker logs"
      alias dclf="docker logs --follow"
      alias dcsh='f() { docker exec -it "$1" bash || docker exec -it "$1" sh; }; f'

- name: Create compose directory
  tags: docker, compose
  file:
    path: "{{ compose_dir }}"
    state: directory
    mode: "0770"
    owner: root
    group: docker

- name: Read /etc/fstab for NFS mounts
  tags: nfs, docker
  slurp:
    path: /etc/fstab
  register: fstab_content

- name: Check if NFS mounts are present
  tags: nfs, docker
  set_fact:
    nfs_configured: "{{ 'nfs' in fstab_content.content | b64decode }}"

- name: Ensure docker starts after NFS if needed
  tags: nfs, docker
  when: nfs_configured
  block:
    - name: Create override directory for docker.service
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        mode: "0755"

    - name: Create override file for docker.service
      copy:
        content: |
          [Unit]
          Requires=nfs-client.target
          After=nfs-client.target
        dest: /etc/systemd/system/docker.service.d/override.conf
        mode: "0644"
      notify: Reload systemd

- name: Copy docker-compose.yml files
  tags: docker, compose
  template:
    src: "{{ item }}"
    dest: "{{ compose_dir }}/{{ item | basename }}"
    mode: "0660"
    owner: root
    group: docker
  with_fileglob:
    - ../templates/{{ inventory_hostname }}/*.yml

- name: Copy .env files
  tags: docker, compose, env
  copy:
    src: "{{ item }}"
    dest: "{{ compose_dir }}/{{ item | basename }}"
    mode: "0440"
    owner: root
    group: docker
  with_fileglob:
    - ../files/{{ inventory_hostname }}/docker_env/*.env

- name: Copy compose .env
  tags: docker, compose, env
  copy:
    src: "{{ inventory_hostname }}/docker_env/compose_env"
    dest: "{{ compose_dir }}/.env"
    mode: "0440"
    owner: root
    group: docker
  ignore_errors: true # file may not exist if not needed

- name: Pull docker services
  tags: docker, compose, pull
  shell:
    chdir: "{{ compose_dir }}"
    executable: /usr/bin/zsh
    cmd: set -o pipefail; docker-compose $(find /opt/doc/*.yml | sed -e "s/^/-f /") pull
  register: result
  # these "changed_when" conditions aren't quite working yet
  changed_when: "'Pull complete' in result.stdout"

- name: Start docker services
  tags: docker, compose, up
  shell:
    chdir: "{{ compose_dir }}"
    executable: /usr/bin/zsh
    cmd: set -o pipefail; docker-compose $(find /opt/doc/*.yml | sed -e "s/^/-f /") up -d --remove-orphans
  register: result
  changed_when: "'Started' in result.stdout"

- name: Prune docker services
  tags: docker, compose,  up
  command:
    cmd: docker system prune -f
  changed_when: false
