---
- name: Set docker env vars/shortcuts
  tags: docker, config
  blockinfile:
    path: /home/{{ user }}/.zshenv
    create: true
    mode: 0600
    owner: "{{ user }}"
    group: "{{ user }}"
    block: |
      export COMPOSE_FILE={{ compose_dir }}docker-compose.yml
      alias dc="docker-compose --project-directory {{ compose_dir }}"
      alias dcls="docker container ls"
      alias dcl="docker logs"
      alias dclf="docker logs --follow"

- name: Create compose directory
  tags: docker, compose
  file:
    path: "{{ compose_dir }}"
    state: directory
    mode: 0770
    owner: root
    group: docker

- name: Copy docker-compose.yml
  tags: docker, compose
  template:
    src: "{{ inventory_hostname }}-compose.yml"
    dest: "{{ compose_dir }}docker-compose.yml"
    mode: 0660
    owner: root
    group: docker

- name: Copy .env
  tags: docker, env
  copy:
    src: "{{ inventory_hostname }}.env"
    dest: "{{ compose_dir }}.env"
    mode: 0440
    owner: root
    group: docker

- name: Pull docker services
  tags: docker, compose
  command:
    chdir: "{{ compose_dir }}"
    cmd: docker-compose pull
  register: result
  # these "changed_when" conditions aren't quite working yet
  changed_when: "'Pull complete' in result.stdout"

- name: Start docker services
  tags: docker, compose
  command:
    chdir: "{{ compose_dir }}"
    cmd: docker-compose up -d
  register: result
  changed_when: "'Started' in result.stdout"

- name: Prune docker services
  tags: docker, compose
  command:
    chdir: "{{ compose_dir }}"
    cmd: docker system prune -f
  changed_when: false
