- name: Make user member of docker group
  tags: docker, config
  user:
    name: "{{ user }}"
    groups: docker
    append: yes

- name: Set docker env vars/shortcuts
  tags: docker, config
  blockinfile:
    path: "/home/{{ user }}/.zshenv"
    create: yes
    block: |
      export COMPOSE_FILE={{ compose_dir }}docker-compose.yml
      alias dc="docker-compose --project-directory {{ compose_dir }}"

- name: Install pip3 and nfs-common
  tags: docker, sdk, nfs
  apt:
    name: 
      - python3-pip
      - nfs-common

- name: Create mountpoints
  tags: config, nfs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop: 
    - /ssd/app
    - /hdd/app
  register: mountpoints

- name: Make mountpoints immutable
  tags: config, nfs
  ansible.builtin.file:
    path: "{{ item }}"
    attributes: +i
  loop: 
    - /ssd/app
    - /hdd/app
  when: mountpoints.changed

- name: Map NFS shares
  tags: config, nfs
  blockinfile:
    path: /etc/fstab
    block: |
      # nextcloud on hdd
      10.0.0.5:/hdd/app	/hdd/app	nfs	auto	0	0

      # other apps on ssd
      10.0.0.5:/ssd/app	/ssd/app	nfs	auto	0	0
  register: nfs
  
- name: Mount network shares
  tags: config, nfs
  shell: mount -a
  when: nfs.changed

- name: Install docker and docker-compose Python modules
  tags: docker, sdk
  pip:
    name: 
    - docker
    - docker-compose

# - name: Pull docker-compose.yml
#   tags: docker, compose, vault
#   git:
#     repo: 'https://{{ git_user }}:{{ git_token }}@gl.<redacted>/<redacted>/docker-compose.git'
#     dest: "{{ compose_dir }}"

- name: Copy docker-compose.yml
  tags: docker, compose
  copy:
    src: docker-compose.yml
    dest: "{{ compose_dir }}"
    mode: 0664
    owner: root
    group: docker 

- name: Copy .env
  tags: docker, compose
  copy:
    src: .env
    dest: "{{ compose_dir }}"
    mode: 0440
    owner: root
    group: docker 

# - name: Tear down existing services
#   tags: docker, compose
#   community.docker.docker_compose:
#     project_src: "{{ compose_dir }}"
#     state: absent

- name: Create and start services
  tags: docker, compose
  community.docker.docker_compose:
    project_src: "{{ compose_dir }}"
    remove_orphans: yes
  register: output
