---
# NFS directories mounted on file server
nfs_dirs:
  - path: /ssd/dmz/app
    user: dmz-doc
    group: dmz-doc
  - path: /ssd/app/games
    user: root
    group: root
# Users/groups for nfs server
custom_groups:
  - name: dmz-doc
    gid: 2010
custom_users:
  - name: dmz-doc
    create_home: false
    uid: 2010
    groups: dmz-doc
  - name: aven
    groups: [dmz-doc, sudo, docker]
  # User for pushing web content from CI pipeline
  - name: web-push
    uid: 2020
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMVUej2tH01md6+Huw6fgsKCDiQtYNfPCJciOtYEX6c9 web-push
