---
- name: Set distro-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- name: Verify ansible and root passwords are locked
  user:
    name: "{{ item }}"
    password_lock: true
  loop:
    - "{{ ansible_user }}"
    - root

- name: Install packages
  package:
    name:
      - vim
      - zsh
      - tldr
      - tmux
      - curl
      - git
      - ufw
      - rsync
      - kitty-terminfo
    state: present

- name: Remove unwanted packages
  package:
    name:
      - nano
    state: absent

- name: Install zsh-grml-config
  tags: zsh, config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    owner: root
    group: root
  loop:
    - { src: zshrc, dest: /etc/zsh/zshrc }
    - { src: zshrc-skel, dest: /etc/skel/.zshrc }
    - { src: zshrc-skel, dest: /etc/zsh/newuser.zshrc.recommended }
    - { src: zshrc-skel, dest: "/home/{{ user }}/.zshrc" }

- name: Set shells to zsh
  tags: zsh, config
  user:
    name: "{{ item }}"
    shell: /bin/zsh
  loop:
    - root
    - "{{ user }}"

- name: Set timezone
  tags: config, tz
  timezone:
    name: "{{ timezone }}"
  notify: Restart cron

- name: Set sshd config
  tags: sshd
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: "0644"
    owner: root
    group: root
    validate: sshd -t -f %s
  notify: Restart sshd

- name: Remove motd
  tags: sshd
  file:
    path: /etc/motd
    state: absent
