- name: Configure pacman
  tags: config
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf
    mode: 0644
    owner: root
    group: root

- name: Install window management packages
  tags: pkg
  package:
    name:
      - xorg-server
      - xorg-xrandr
      - xorg-xrdb
      - lightdm
      - lightdm-gtk-greeter
      - i3-wm  
      - i3blocks  
      - i3lock
      - i3status
      - dmenu
      - xterm
      # For VM only
      # - xf86-video-qxl
      # - spice-vdagent


- name: Enable lightdm service
  tags: pkg
  service:
    name: lightdm
    enabled: yes
    state: started

- name: Install workstation software packages
  tags: pkg
  package:
    name:
      # User apps
      - audacity # audio editor
      - code # de-Microsofted VS Code fork
      - digikam # photo manager
      - discord # social client
      - firefox # web browser
      - gimp # image editor
      - keepassxc # password manager
      - libreoffice-fresh # office software
      - musescore # sheet music editor
      - nextcloud-client # file synchronization
      - nitrogen # background manager
      - obs-studio # screen recorder
      - libqalculate # CLI calculator
      - redshift # blue light reducer
      - signal-desktop # messenger
      - steam # games
      - thunar # file browser
      - thunar-archive-plugin # archive support
      - thunar-volman # removable media management
      - tldr # concise, useful manpages
      - tmux # terminal multiplexer
      - transmission-gtk # torrent client
      - veracrypt # file encryption
      - vim # vim
      - vim-ansible # ansible highlighting
      - virt-viewer # SPICE client
      - vlc # media player
      - youtube-dl # youtube downloader

      # System utilities
      - ansible # config manager
      - ark # archive manager
      - baobab # disk usage analyser
      - cowsay # cowsay
      - eog # image viewer
      - fd # find, but better
      - iftop # network monitor
      - networkmanager # network manager
      - nmap # network mapper
      - nvidia # proprietary drivers
      - nvidia-settings # nvidia x server settings
      - nvtop # GPU monitor
      - kitty # terminal emulator
      - neofetch # OS info
      - pv # progress viewer
      - reflector # pacman mirror manager
      - rkhunter # rootkit hunter
      - rsync # copy files in style
      - seahorse # keyring viewer
      - testdisk # data recovery
      - traceroute # traceroute
      - tree # directory viewer
      - unzip # unzips
      - wireshark-qt # protocol analyzer
      - xev # view key events
      - zip # zips

      # Helpers and styling
      - breeze-icons # icon theme
      - ccid # smart card driver
      - dunst # notification daemon
      - file-roller # archive support for thunar
      - freetype2 # font rendering
      - gnome-keyring # keyring
      - gvfs # removable storage mounting
      - nss-mdns # mdns name resolution
      - opensc # smart card libraries
      - pasystray # PulseAudio tray icon
      - pavucontrol # PulseAudio volume control
      - pulseaudio # The man himself
      - ttf-fira-code # nice font
      - tumbler # thumbnails for thunar

- name: Install AUR packages
  tags: pkg, aur
  become: false
  kewlfft.aur.aur:
    name:
      - j4-make-config-git # i3 config helper
      - brother-hll2350dw # print drivers 
      - magic-wormhole # file transfer
      - vmware-horizon-client # remote desktop client
      - vmware-horizon-smartcard # smartcard support
      - protonvpn # ProtonVPN CLI and GUI
      - standardnotes-desktop # notes
      - spotify # music
      - typora-free # markdown editor/exporter
      - autotiling # i3 window tiling
      - i3lock-multimonitor # mutimonitor support for i3lock
    state: present

- name: Configure lightdm-gtk-greeter
  tags: pkg, config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: root
    group: root 
  loop:
    - { src: "lightdm-gtk-greeter.conf", dest: "/etc/lightdm/lightdm-gtk-greeter.conf" }
    - { src: "greeter.png", dest: "/etc/lightdm/greeter.png" }
