---
- name: Install nfs-common
  tags: nfs
  apt:
    name: nfs-common

- name: Create mountpoints
  tags: config, nfs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0770
  loop: "{{ nfs_dirs }}"
  register: mountpoints

- name: Make mountpoints immutable
  tags: config, nfs
  ansible.builtin.file:
    path: "{{ item }}"
    attributes: +i
  loop: "{{ nfs_dirs }}"
  when: mountpoints.changed

- name: Map NFS shares
  tags: config, nfs
  lineinfile:
    path: /etc/fstab
    regexp: "{{ item }}"
    # /etc/fstab traditionally has tabs, so skip no-tab linting rule
    line: "10.0.0.5:{{ item }}\t{{ item }}\tnfs\tauto\t0\t0" # noqa no-tabs
  loop: "{{ nfs_dirs }}"
  register: nfs
