---
- name: Install nfs-common
  tags: nfs
  apt:
    name: nfs-common

- name: Create mountpoints
  tags: config, nfs
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    mode: 0770
  loop: "{{ nfs_dirs }}"
  notify: Make mountpoints immutable

- name: Map NFS shares
  tags: config, nfs
  lineinfile:
    path: /etc/fstab
    regexp: "{{ item.path }}"
    # /etc/fstab traditionally has tabs, so skip no-tab linting rule
    line: "10.0.0.2:{{ item.path }}\t{{ item.path }}\tnfs\tauto\t0\t0" # noqa no-tabs
  loop: "{{ nfs_dirs }}"
