---
- name: Install nfs-common
  tags: nfs
  apt:
    name: nfs-common

- name: Create mountpoints
  tags: config, nfs
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    mode: "0770"
  loop: "{{ nfs_dirs }}"
  notify: Make mountpoints immutable

# Mark mountpoints as immutable (if created) before mounting
- name: Flush handlers
  tags: config, nfs
  meta: flush_handlers

# We need the nfs client to shut down before the tailscale tunnel goes down
- name: Add lines to nfs-client.target
  tags: config, nfs
  lineinfile:
    path: /etc/systemd/system/remote-fs.target.wants/nfs-client.target
    insertafter: ^Before=
    line: "{{ item }}"
  with_items:
    - After=tailscaled.service
    - Wants=tailscaled.service
  when: "'tailscale0' in ansible_interfaces"
  notify: Reload systemd

- name: Mount NFS shares
  tags: config, nfs
  ansible.posix.mount:
    src: "{{ item.server }}:{{ item.path }}"
    path: "{{ item.path }}"
    opts: rw
    state: mounted
    fstype: nfs
  loop: "{{ nfs_dirs }}"
