---
- name: Install nfs-common
  tags: nfs
  apt:
    name: nfs-common

- name: Create mountpoints
  tags: config, nfs
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    mode: "0770"
  loop: "{{ nfs_dirs }}"
  notify: Make mountpoints immutable

- name: Add NFS groups
  tags: users, groups, nfs, config
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid | default(omit) }}"
  loop: "{{ nfs_groups }}"

- name: Add NFS users
  tags: users, nfs, config
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
    create_home: "{{ item.create_home | default(True) }}"
  loop: "{{ nfs_users }}"

- name: Map NFS shares
  tags: config, nfs
  ansible.posix.mount:
    src: "{{ nfs_server_ip }}:{{ item.path }}"
    path: "{{ item.path }}"
    state: mounted
    fstype: nfs
  loop: "{{ nfs_dirs }}"
