- name: Install nfs-common
  tags: nfs
  apt:
    name: nfs-common

- name: Create mountpoints
  tags: config, nfs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop: "{{ nfs_dirs }}"
  register: mountpoints

- name: Make mountpoints immutable
  tags: config, nfs
  ansible.builtin.file:
    path: "{{ item }}"
    attributes: +i
  loop: "{{ nfs_dirs }}"
  when: mountpoints.changed

- name: Map NFS shares
  tags: config, nfs
  lineinfile:
    path: /etc/fstab
    regexp: "{{ item }}"
    line: 10.0.0.5:{{ item }}	{{ item }}	nfs	auto	0	0
  loop: "{{ nfs_dirs }}"
  register: nfs