---
- name: Configure pacman
  tags: config
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf
    mode: "0644"
    owner: root
    group: root

- name: Install window management packages
  tags: pkg, update
  package:
    name:
      - xorg-server
      - xorg-xrandr
      - xorg-xrdb
      - lightdm
      - lightdm-gtk-greeter
      - i3-wm
      - i3blocks
      - polybar # customizable statusbar
      - dmenu
      - xterm
      - xss-lock
      # For VM only
      # - xf86-video-qxl
      # - spice-vdagent

- name: Enable and start lightdm
  tags: pkg
  service:
    name: lightdm
    enabled: true
    state: started

- name: Install packages
  include_tasks: packages.yaml

- name: Enable and start services
  tags: pkg
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - lightdm
    - systemd-timesyncd
    - cups
    - avahi-daemon
    - pcscd
    - bluetooth
    - incrond

- name: Enable services
  tags: pkg
  service:
    name: "{{ item }}"
    enabled: true
  loop:
    - reflector
    - nvidia-suspend
    - nvidia-hibernate

- name: Configure lightdm-gtk-greeter
  tags: pkg, config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    owner: root
    group: root
  loop:
    - { src: lightdm-gtk-greeter.conf, dest: /etc/lightdm/lightdm-gtk-greeter.conf }
    - { src: greeter.png, dest: /etc/lightdm/greeter.png }

- name: Configure mouse input
  tags: config
  copy:
    src: mouse.conf
    dest: /etc/X11/xorg.conf.d/99-libinput-custom.conf
    mode: "0644"
    owner: root
    group: root

- name: Configure fonts
  tags: config
  copy:
    src: fonts.conf
    dest: /etc/fonts/local.conf
    mode: "0644"
    owner: root
    group: root

- name: Create audio output switcher script
  tags: config, script
  copy:
    src: switch_audio_out.sh
    dest: /usr/local/bin/switch_audio_out
    mode: "0755"
    owner: root
    group: root

- name: Configure git
  tags: git, config
  copy:
    src: .gitconfig
    dest: /home/{{ user }}/.gitconfig
    mode: "0644"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Configure refind
  tags: refind, config
  blockinfile:
    path: /boot/EFI/refind/refind.conf
    create: true
    mode: "0600"
    block: |-
      # Don't wear out NVRAM
      use_nvram false
      # Use native resolution, if supported by EFI
      resolution max
      # Makes Windows boot look a little nicer
      use_graphics_for windows
      # Automatically boot last OS after timeout
      timeout 10

      # refind-theme-regular settings
      icons_dir themes/refind-theme-regular/icons/384-144
      big_icon_size 384
      small_icon_size 144
      banner themes/refind-theme-regular/icons/384-144/bg_dark.png
      selection_big themes/refind-theme-regular/icons/384-144/selection_dark-big.png
      selection_small themes/refind-theme-regular/icons/384-144/selection_dark-small.png
      font themes/refind-theme-regular/fonts/source-code-pro-extralight-14.png

# This is the most elegant way I've found to get refind to use the correct icons
# for my OSes: replacing the default autodetected icons with my desired ones.
- name: Configure refind icons
  tags: refind, config
  copy:
    remote_src: true
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    owner: root
    group: root
  loop:
    - src: /boot/EFI/refind/themes/refind-theme-regular/icons/384-144/os_arch.png
      dest: /boot/EFI/refind/themes/refind-theme-regular/icons/384-144/os_linux.png
    - src: /boot/EFI/refind/themes/refind-theme-regular/icons/384-144/os_win11.png
      dest: /boot/EFI/refind/themes/refind-theme-regular/icons/384-144/os_win8.png

- name: Create Horizon remote desktop dir
  tags: horizon, config
  file:
    dest: /usr/lib/vmware/view/pkcs11
    state: directory
    mode: "0755"

- name: Configure Horizon remote desktop
  tags: horizon, config
  file:
    src: /usr/lib64/pkcs11/opensc-pkcs11.so
    dest: /usr/lib/vmware/view/pkcs11/libopenscpkcs11.so
    state: link
    mode: "0644"

- name: Power Bluetooth adapter on startup
  tags: config
  blockinfile:
    path: /etc/bluetooth/main.conf
    block: |-
      [Policy]
      AutoEnable=true

- name: Create gtk theme dir
  tags: config, theme
  file:
    path: /home/{{ user }}/.config/gtk-3.0
    state: directory
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Configure gtk theme
  tags: config, theme
  blockinfile:
    path: /home/{{ user }}/.config/gtk-3.0/settings.ini
    create: true
    mode: "0644"
    owner: "{{ user }}"
    group: "{{ user }}"
    block: |-
      [Settings]
      gtk-icon-theme-name = Catppuccin-Macchiato-Peach
      gtk-theme-name = Catppuccin-Macchiato-Peach
      gtk-application-prefer-dark-theme = true

- name: Save VRAM on suspend
  tags: system
  blockinfile:
    path: /etc/modprobe.d/nvidia-power-management.conf
    create: true
    mode: "0644"
    # This needs to be stored on an fs with enough room, so we'll put it in /home
    block: |-
      options nvidia NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/home/{{ user }}/.cache/

- name: Create video in/out dirs
  tags: config
  file:
    name: /home/{{ user }}/Videos/{{ item }}
    state: directory
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ user }}"
  loop:
    - convert_in
    - convert_out

- name: Configure incrond
  tags: config
  lineinfile:
    path: /var/spool/incron/{{ user }}
    create: true
    mode: "0600"
    owner: "{{ user }}"
    group: "{{ user }}"
    line: >
      /home/{{ user }}/Videos/convert_in IN_CLOSE_WRITE /usr/bin/ffmpeg -i $@/$# -c:v dnxhd -profile:v dnxhr_hq -pix_fmt yuv422p -c:a pcm_s16le -f mov /home/{{
      user }}/Videos/convert_out/$# && trash-put $@/$# 
