---
- name: Configure pacman
  tags: config
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf
    mode: 0644
    owner: root
    group: root

- name: Install window management packages
  tags: pkg, update
  package:
    name:
      - xorg-server
      - xorg-xrandr
      - xorg-xrdb
      - lightdm
      - lightdm-gtk-greeter
      - i3-wm
      - i3blocks
      - i3lock
      - polybar # customizable statusbar
      - dmenu
      - xterm
      - xss-lock
      # For VM only
      # - xf86-video-qxl
      # - spice-vdagent

- name: Enable lightdm
  tags: pkg
  service:
    name: lightdm
    enabled: true
    state: started

- name: Enable timesyncd
  tags: pkg
  service:
    name: systemd-timesyncd
    enabled: true
    state: started

- name: Install workstation software packages
  tags: pkg, update
  package:
    name:
      # User apps
      - audacity # audio editor
      - code # de-Microsofted VS Code fork
      - digikam # photo manager
      - discord # social client
      - firefox # web browser
      - gimp # image editor
      - keepassxc # password manager
      - libreoffice-fresh # office software
      - musescore # sheet music editor
      - nextcloud-client # file synchronization
      - nitrogen # background manager
      - obs-studio # screen recorder
      - libqalculate # CLI calculator
      - redshift # blue light reducer
      - signal-desktop # messenger
      - steam # games
      - thunar # file browser
      - thunar-archive-plugin # archive support
      - thunar-volman # removable media management
      - thunderbird # email
      - tldr # concise, useful manpages
      - tmux # terminal multiplexer
      - transmission-gtk # torrent client
      - veracrypt # file encryption
      - vim # vim
      - vim-ansible # ansible highlighting
      - virt-viewer # SPICE client
      - vlc # media player
      - youtube-dl # youtube downloader

      # System utilities
      - ansible # config manager
      - ark # archive manager
      - baobab # disk usage analyser
      - bat # better cat
      - cowsay # cowsay
      - dnsutils # dig
      - docker # containers
      - docker-compose # container management
      - duf # better df
      - eog # image viewer
      - fd # better find
      - git # git
      - hexyl # better xxd
      - iftop # network monitor
      - networkmanager # network manager
      - nmap # network mapper
      - nvidia # proprietary drivers
      - nvidia-settings # X server settings
      - nvtop # GPU monitor
      - kitty # terminal emulator
      - neofetch # OS info
      - perl-image-exiftool # metadata parser
      - pv # progress viewer
      - reflector # pacman mirror manager
      - rkhunter # rootkit hunter
      - rsync # copy files in style
      - seahorse # keyring viewer
      - tcpdump # peep some packets
      - testdisk # data recovery
      - traceroute # traceroute
      - tree # directory viewer
      - unzip # unzips
      - wireshark-qt # protocol analyzer
      - xorg-xev # view key events
      - zip # zips

      # Helpers and styling
      - base-devel # needed for AUR
      - breeze-icons # icon theme
      - ccid # smart card driver
      - dunst # notification daemon
      - file-roller # archive support for thunar
      - freetype2 # font rendering
      - gnome-keyring # keyring
      - gvfs # removable storage mounting
      - network-manager-applet # tray icon, ProtonVPN dependency
      - nss-mdns # mdns name resolution
      - opensc # smart card libraries
      - pasystray # PulseAudio tray icon
      - pavucontrol # PulseAudio volume control
      - pulseaudio # the man himself
      - ttf-fira-code # nice font
      - tumbler # thumbnails for thunar

- name: Install yay
  tags: pkg, aur, update
  become: false
  kewlfft.aur.aur:
    name:
      - yay # AUR manager

- name: Install AUR packages
  tags: pkg, aur, update
  become: false
  kewlfft.aur.aur:
    name:
      - autotiling # i3 window tiling
      - brother-hll2350dw # print drivers
      - i3lock-multimonitor # mutimonitor support for i3lock
      - magic-wormhole # file transfer
      - protonmail-bridge # allows local use of ProtonMail
      - protonvpn # ProtonVPN CLI and GUI
      - refind-theme-regular-git # theme for refind
      - spotify # music
      - standardnotes-desktop # notes
      - typora-free # markdown editor/exporter
      - vmware-horizon-client # remote desktop client
      - vmware-horizon-smartcard # smartcard support
    state: present

- name: Configure lightdm-gtk-greeter
  tags: pkg, config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: root
    group: root
  loop:
    - { src: lightdm-gtk-greeter.conf, dest: /etc/lightdm/lightdm-gtk-greeter.conf }
    - { src: greeter.png, dest: /etc/lightdm/greeter.png }

- name: Configure mouse input
  tags: config
  copy:
    src: mouse.conf
    dest: /etc/X11/xorg.conf.d/99-libinput-custom.conf
    mode: 0644
    owner: root
    group: root

- name: Configure fonts
  tags: config
  copy:
    src: fonts.conf
    dest: /etc/fonts/local.conf
    mode: 0644
    owner: root
    group: root

- name: Create audio output switcher script
  tags: config, script
  copy:
    src: switch_audio_out.sh
    dest: /usr/local/bin/switch_audio_out
    mode: 0755
    owner: root
    group: root

- name: Configure git
  tags: git, config
  copy:
    src: .gitconfig
    dest: /home/{{ user }}/.gitconfig
    mode: 0644
    owner: "{{ user }}"
    group: "{{ user }}"
