version: '3.7'

services:
  mc-survival-2:
    container_name: mc-survival-2
    # mods require java 8
    # autopause has issues on alpine with java8 image
    image: itzg/minecraft-server:java8-openj9
    restart: unless-stopped

    ports:
      - 25567:25565

    volumes:
      - '/ssd/app/games/minecraft/mc-survival-201122-1.16.4:/data'

    environment:
      TZ: 'America/Chicago'
      EULA: 'True'
      PVP: 'false'
      DIFFICULTY: 'normal'
      SERVER_NAME: 'The Shattered Plains'
      OPS: ${MINECRAFT_OP}
      MEMORY: '3G'
      MOTD: 'The Shattered Plains'
      TYPE: 'FORGE'
      VERSION: "1.16.4"
      # ENABLE_AUTOPAUSE: "TRUE"
      # AUTOPAUSE_TIMEOUT_EST: 60
      # AUTOPAUSE_TIMEOUT_INIT: 60
      # DISABLE_HEALTHCHECK: "True"

  mc-survival-3:
    container_name: mc-survival-3
    image: itzg/minecraft-server:java17
    restart: unless-stopped

    ports:
      - 25568:25565

    volumes:
      - '/ssd/app/games/minecraft/mc-survival-211205-1.18.0:/data'

    environment:
      TZ: 'America/Chicago'
      EULA: 'True'
      PVP: 'false'
      DIFFICULTY: 'normal'
      SERVER_NAME: 'Haven Grotto'
      OPS: ${MINECRAFT_OP}
      MEMORY: '3G'
      MOTD: 'Haven Grotto'
      TYPE: 'FORGE'
      VERSION: "1.18.2"
      # ENABLE_AUTOPAUSE: "TRUE"
      # AUTOPAUSE_TIMEOUT_EST: 60
      # AUTOPAUSE_TIMEOUT_INIT: 60
      # DISABLE_HEALTHCHECK: "True"

  ror2:
    container_name: ror2
    image: avivace/ror2server:latest
    restart: unless-stopped

    ports:
      - 27015:27015/udp

    environment:
      R2_PSW: ${ROR2_PASS}

  factorio:
    container_name: factorio
    image: factoriotools/factorio:stable
    restart: unless-stopped
    
    ports:
      - 34197:34197/udp
      - 27015:27015/tcp

    volumes:
      - /ssd/app/games/factorio/loriini:/factorio

    environment:
      UPDATE_MODS_ON_START: 'true'
      SAVE_NAME: "Loriini"

